/**
 * @file gap-report command — File a gap report for missing XDS capabilities
 *
 * Interactive and non-interactive modes for reporting gaps in the design system.
 * Creates GitHub issues with the `gap-report` label.
 *
 * Includes `gap-report setup` subcommand for configuring gap report delivery.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as p from '@clack/prompts';
import {
  checkGhCli,
  createGapReport,
  loadGapReportConfig,
  GAP_CATEGORIES,
} from '../utils/github.mjs';
import {getRunPrefix} from '../utils/package-manager.mjs';

function isCancel(value) {
  if (p.isCancel(value)) {
    p.cancel('Gap report cancelled.');
    process.exit(0);
  }
  return value;
}

/**
 * Update or insert the gapReport key in xds.config.mjs.
 * Preserves existing keys (e.g. theme).
 */
function writeGapReportConfig(targetDir, gapReportValue) {
  const configPath = path.join(targetDir, 'xds.config.mjs');

  if (fs.existsSync(configPath)) {
    let content = fs.readFileSync(configPath, 'utf-8');

    // Replace existing gapReport key (handles both `false` and `{ command: '...' }`)
    if (/gapReport\s*:/.test(content)) {
      content = content.replace(
        /gapReport\s*:\s*(?:\{[^}]*\}|false|true)\s*,?/s,
        `gapReport: ${gapReportValue},`,
      );
    } else {
      // Insert before the closing `};`
      content = content.replace(
        /(\n};?\s*)$/,
        `\n  gapReport: ${gapReportValue},$1`,
      );
    }

    fs.writeFileSync(configPath, content);
  } else {
    const content = `/**
 * XDS Configuration
 * Generated by \`xds gap-report setup\`
 */
export default {
  gapReport: ${gapReportValue},
};
`;
    fs.writeFileSync(configPath, content);
  }

  return configPath;
}

export function registerGapReport(program) {
  const gapCmd = program
    .command('gap-report')
    .description('Report a gap in the XDS design system');

  // --- setup subcommand ---
  gapCmd
    .command('setup')
    .description('Configure where gap reports are sent')
    .action(async () => {
      p.intro('Gap report setup');

      const config = loadGapReportConfig();
      const currentMode = !config.enabled
        ? 'disabled'
        : config.command
          ? 'custom'
          : 'github';

      const mode = isCancel(
        await p.select({
          message: `How should gap reports be delivered? (current: ${currentMode})`,
          options: [
            {
              value: 'github',
              label: 'GitHub Issues',
              hint: 'Creates issues on facebookexperimental/xds (requires gh CLI)',
            },
            {
              value: 'custom',
              label: 'Custom command',
              hint: 'Run a script that receives the report as JSON on stdin',
            },
            {
              value: 'disabled',
              label: 'Disabled',
              hint: 'Turn off gap reporting entirely',
            },
          ],
        }),
      );

      let configValue;
      const targetDir = process.cwd();

      if (mode === 'disabled') {
        configValue = 'false';
        writeGapReportConfig(targetDir, configValue);
        p.log.success('Gap reporting disabled.');
      } else if (mode === 'custom') {
        const command = isCancel(
          await p.text({
            message: 'Path to script:',
            placeholder: './scripts/report-gap.sh',
            validate: val => {
              if (!val.trim()) return 'Script path is required';
            },
          }),
        );

        configValue = `{ command: '${command.trim()}' }`;
        writeGapReportConfig(targetDir, configValue);

        p.log.success(`Gap reports will be sent to: ${command.trim()}`);
        p.note(
          'Your script receives JSON on stdin with these fields:\n' +
            '  component, category, categoryLabel, intention,\n' +
            '  detail, source, timestamp\n\n' +
            'Anything printed to stdout is shown to the user.',
          'Script contract',
        );
      } else {
        // GitHub mode — remove gapReport key or set to default
        const configPath = path.join(targetDir, 'xds.config.mjs');
        if (fs.existsSync(configPath)) {
          let content = fs.readFileSync(configPath, 'utf-8');
          // Remove the gapReport line entirely to use default
          content = content.replace(
            /\s*gapReport\s*:\s*(?:\{[^}]*\}|false|true)\s*,?/s,
            '',
          );
          fs.writeFileSync(configPath, content);
        }

        if (!checkGhCli()) {
          p.log.warning(
            'gh CLI is not installed or not authenticated.\n' +
              'Install from https://cli.github.com and run `gh auth login`.',
          );
        } else {
          p.log.success(
            'Gap reports will create GitHub issues on facebookexperimental/xds.',
          );
        }
      }

      p.outro('Configuration saved to xds.config.mjs');
    });

  // --- main gap-report command ---
  gapCmd
    .option('--component <name>', 'Component name')
    .option('--category <category>', 'Gap category')
    .option('--reason <reason>', 'What capability was missing')
    .action(async options => {
      const config = loadGapReportConfig();
      if (!config.enabled) {
        console.log(
          `Gap reporting is disabled. Run \`${getRunPrefix()} xds gap-report setup\` to configure.`,
        );
        return;
      }

      if (!config.command && !checkGhCli()) {
        console.error(
          'Error: GitHub CLI (gh) is not installed or not authenticated.\n' +
            'Install it from https://cli.github.com and run `gh auth login`.\n\n' +
            `Or run \`${getRunPrefix()} xds gap-report setup\` to configure a custom command.`,
        );
        process.exit(1);
      }

      const isNonInteractive =
        options.component && options.category && options.reason;

      if (isNonInteractive) {
        // Non-interactive mode for LLM/script use
        const validCategory = GAP_CATEGORIES.find(
          c => c.value === options.category,
        );
        if (!validCategory) {
          console.error(
            `Error: Invalid category "${options.category}".\n` +
              `Valid categories: ${GAP_CATEGORIES.map(c => c.value).join(', ')}`,
          );
          process.exit(1);
        }

        try {
          const url = createGapReport({
            component: options.component,
            category: options.category,
            intention: options.reason,
            source: 'cli',
          });
          if (url) {
            console.log(`\n✓ Gap report filed: ${url}\n`);
          } else {
            console.log('\nGap reporting is disabled via configuration.\n');
          }
        } catch (err) {
          console.error(`Error filing gap report: ${err.message}`);
          process.exit(1);
        }
        return;
      }

      // Interactive mode
      p.intro('Report an XDS gap');

      const component = isCancel(
        await p.text({
          message: 'Which component is this about?',
          placeholder: 'e.g. Button, Table, or "general"',
          validate: val => {
            if (!val.trim()) return 'Component name is required';
          },
        }),
      );

      const category = isCancel(
        await p.select({
          message: 'What kind of gap is this?',
          options: GAP_CATEGORIES,
        }),
      );

      const intention = isCancel(
        await p.text({
          message: 'What were you trying to achieve?',
          placeholder:
            'e.g. "Need a compact variant for use in dense data tables"',
          validate: val => {
            if (!val.trim()) return 'Please describe what you were trying to do';
          },
        }),
      );

      const detail = isCancel(
        await p.text({
          message: 'Any additional context? (optional)',
          placeholder: 'Press Enter to skip',
        }),
      );

      const s = p.spinner();
      s.start('Filing gap report');

      try {
        const url = createGapReport({
          component: component.trim(),
          category,
          intention: intention.trim(),
          detail: detail?.trim() || undefined,
          source: 'interactive',
        });
        s.stop(url ? 'Gap report filed' : 'Gap reporting is disabled');
        if (url) {
          p.log.success(url);
        }
      } catch (err) {
        s.stop('Failed to file gap report');
        p.log.error(err.message);
        process.exit(1);
      }

      p.outro('Thanks for the feedback!');
    });
}
