#!/usr/bin/env node
// Copyright (c) Meta Platforms, Inc. and affiliates.

/**
 * Generates apps/docsite/src/generated/playground-scope.ts
 *
 * Maps every XDS module available in the playground preview iframe.
 * This runs as part of `pnpm generate` (before dev/build) so new components
 * are picked up automatically — no manual maintenance needed.
 *
 * Run: node scripts/generate-scope.mjs
 */

import {readFileSync, writeFileSync, mkdirSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const CORE_PKG = resolve(ROOT, '../../packages/core/package.json');
const OUT = resolve(ROOT, 'src/generated/playground-scope.ts');

const HEADER = `// Copyright (c) Meta Platforms, Inc. and affiliates.

// @generated by scripts/generate-scope.mjs — do not edit manually`;

// Read core package.json exports and extract PascalCase component subpaths
const corePkg = JSON.parse(readFileSync(CORE_PKG, 'utf-8'));
const exportKeys = Object.keys(corePkg.exports ?? {});

const SKIP = /\.(css|stylex)$|\/utils$|^\.\/theme|^\.\/hooks|^\.\/utils|^\.\/syntax|^\.\/docs|^\.\/groups|^\.$|^\.\/reset/;

const components = exportKeys
  .filter((k) => {
    if (SKIP.test(k)) return false;
    const name = k.replace('./', '');
    return /^[A-Z]/.test(name);
  })
  .map((k) => k.replace('./', ''));

// Themes — add new themes here as they become available
const SCOPE_THEMES = [
  {pkg: '@xds/theme-default', name: 'defaultTheme', subpath: '/built'},
  {pkg: '@xds/theme-neutral', name: 'neutralTheme', subpath: '/built'},
  {pkg: '@xds/theme-matcha', name: 'matchaTheme', subpath: '/built'},
];

// Heroicons variants — exposed alongside Lucide so playground snippets
// and shared template code that still imports from '@heroicons/react/*'
// keeps rendering. New docsite code authors against Lucide; these entries
// are purely for playground runtime compatibility.
const HEROICON_VARIANTS = [
  {path: '16/solid', alias: 'Heroicons16Solid'},
  {path: '20/solid', alias: 'Heroicons20Solid'},
  {path: '24/outline', alias: 'Heroicons24Outline'},
  {path: '24/solid', alias: 'Heroicons24Solid'},
];


// Build output — matches the structure of the previously committed scope.ts
const lines = [HEADER, ''];

// ── React ──────────────────────────────────────────────────────────────
lines.push("import React, {useState, useCallback, useMemo, useEffect, useRef} from 'react';");
lines.push('');

// ── StyleX mock ────────────────────────────────────────────────────────
lines.push(`const stylexMock = {
  create: <T extends Record<string, unknown>>(styles: T): T => styles,
  props: (..._styles: unknown[]) => {
    const style: Record<string, string> = {};
    return {className: '', style};
  },
  defineVars: <T extends Record<string, unknown>>(tokens: T): T => tokens,
  keyframes: (kf: Record<string, Record<string, string>>) => kf,
  types: {
    angle: (v: string) => v,
    color: (v: string) => v,
    image: (v: string) => v,
    integer: (v: string) => v,
    length: (v: string) => v,
    lengthPercentage: (v: string) => v,
    number: (v: string) => v,
    percentage: (v: string) => v,
    resolution: (v: string) => v,
    time: (v: string) => v,
    transformFunction: (v: string) => v,
    transformList: (v: string) => v,
    url: (v: string) => v,
  },
};`);
lines.push('');

// ── Component imports ──────────────────────────────────────────────────
for (const name of components) {
  lines.push(`import * as ${name} from '@xds/core/${name}';`);
}
lines.push('');

// ── Theme imports ──────────────────────────────────────────────────────
for (const t of SCOPE_THEMES) {
  lines.push(`import {${t.name}} from '${t.pkg}${t.subpath}';`);
}
lines.push('');

// ── XDSTheme + tokens ──────────────────────────────────────────────────
lines.push("import {XDSTheme} from '@xds/core/theme';");
lines.push("import type {XDSDefinedTheme} from '@xds/core/theme';");
lines.push("import {createElement, type ComponentProps} from 'react';");
lines.push("import * as xdsTokens from '@xds/core/theme/tokens.stylex';");
lines.push('');

// ── Icon libraries ─────────────────────────────────────────────────────
lines.push("import * as LucideIcons from 'lucide-react';");
lines.push('// Heroicons kept available in the playground scope alongside Lucide');
lines.push("// so template / example code that still imports from");
lines.push("// '@heroicons/react/*' continues to render. New docsite code authors");
lines.push('// against Lucide; these entries are purely for backwards compat.');
for (const h of HEROICON_VARIANTS) {
  lines.push(`import * as ${h.alias} from '@heroicons/react/${h.path}';`);
}
lines.push('');

// ── ControlledXDSTheme wrapper ─────────────────────────────────────────
const themeEntries = SCOPE_THEMES.map(
  (t) => `  ${t.name.replace('Theme', '').toLowerCase()}: ${t.name},`,
).join('\n');

lines.push(`const SCOPE_THEMES: Record<string, XDSDefinedTheme> = {
${themeEntries}
};

const ControlledXDSTheme = (props: ComponentProps<typeof XDSTheme>) => {
  const win =
    typeof window !== 'undefined'
      ? (window as unknown as Record<string, unknown>)
      : null;
  const mode =
    (win?.__xds_preview_mode__ as 'light' | 'dark' | 'system') || 'system';
  const themeName = (win?.__xds_preview_theme__ as string) || 'default';
  const theme = SCOPE_THEMES[themeName] ?? ${SCOPE_THEMES[0].name};
  return createElement(XDSTheme, {...props, theme, mode});
};`);
lines.push('');

// ── Scope map ──────────────────────────────────────────────────────────
lines.push('export const scope: Record<string, Record<string, unknown>> = {');

// react
lines.push(`  react: {
    default: React,
    ...React,
    useState,
    useCallback,
    useMemo,
    useEffect,
    useRef,
  },`);

// stylex
lines.push("  '@stylexjs/stylex': {default: stylexMock, ...stylexMock},");
lines.push("  stylex: {default: stylexMock, ...stylexMock},");

// themes
for (const t of SCOPE_THEMES) {
  lines.push(`  '${t.pkg}': {default: ${t.name}, ${t.name}},`);
  lines.push(`  '${t.pkg}/built': {default: ${t.name}, ${t.name}},`);
}

// XDSTheme (controlled wrapper)
lines.push("  '@xds/core/theme': {XDSTheme: ControlledXDSTheme},");

// tokens.stylex
lines.push("  '@xds/core/theme/tokens.stylex': xdsTokens,");

// Per-component subpath entries
for (const name of components) {
  lines.push(`  '@xds/core/${name}': ${name},`);
}

// Barrel export — all components spread
const spreads = components.map((n) => `    ...${n},`).join('\n');
lines.push(`  '@xds/core': {
${spreads}
  },`);

// Lucide icons + Heroicons
lines.push("  'lucide-react': LucideIcons,");
for (const h of HEROICON_VARIANTS) {
  lines.push(`  '@heroicons/react/${h.path}': ${h.alias},`);
}

// next/image stub
lines.push(`  'next/image': {
    default: (props: Record<string, unknown>) =>
      React.createElement('img', props),
  },`);

lines.push('};');
lines.push('');

// Write output
mkdirSync(dirname(OUT), {recursive: true});
writeFileSync(OUT, lines.join('\n'));
console.log(`✓ Generated ${OUT}`);
console.log(`  ${components.length} components`);
console.log(`  ${SCOPE_THEMES.length} themes`);
console.log(`  lucide-react icons + ${HEROICON_VARIANTS.length} heroicon variants`);
