/**
 * XDS Default Theme
 *
 * The reference theme — provides the standard XDS visual language.
 * Uses defineTheme for CSS-based theming (no StyleX build required for consumers).
 *
 * Typography sizing is driven by typography.scale, which auto-generates both
 * the token values (--text-heading-1-size, --text-body-size, etc.) and the
 * component override rules (.xds-heading.level-1 { font-size: ... }).
 *
 * Only non-typography component overrides need to be specified manually.
 */

import {defineTheme, defineSyntaxTheme} from '@xds/core/theme';
import {defaultIconRegistry} from './icons';

/** Default syntax palette — tuned to the XDS blue color ramp. */
const defaultSyntax = defineSyntaxTheme({
  name: 'xds-default',
  tokens: {
    keyword: ['#0064E0', '#2694FE'],
    string: ['#09441F', '#A5F690'],
    comment: ['#4E606F', '#6B7D8D'],
    number: ['#6B2203', '#FDB876'],
    function: ['#042F97', '#AFD7FF'],
    type: ['#3E0697', '#B3B0FE'],
    variable: ['#0A1317', '#DFE2E5'],
    operator: ['#006D75', '#56C8D8'],
    constant: ['#6B2203', '#FDB876'],
    tag: ['#7B0210', '#FFB2B8'],
    attribute: ['#7A4F1A', '#E8C580'],
    property: ['#006064', '#B2EBF2'],
    punctuation: ['#65737E', '#6F747C'],
    background: ['#F1F4F7', '#111112'],
  },
});

export const defaultTheme = defineTheme({
  name: 'default',

  // Typography: base=14px, ratio=1.2, h4 anchored to base.
  // Generates all heading + text tokens AND component overrides automatically.
  typography: {scale: {base: 14, ratio: 1.2}},

  // Motion: base durations from Ted's proposal (#674), ratio=0.75.
  // Generates: fast-min=130ms, fast=175ms, fast-max=235ms,
  //            medium-min=310ms, medium=410ms, medium-max=545ms.
  motion: {fast: 175, medium: 410, ratio: 0.75},

  // Syntax highlighting — tuned to the default palette
  syntax: defaultSyntax,

  // The default theme uses the built-in token defaults from tokens.stylex.ts.
  tokens: {},

  components: {
    // =========================================================================
    // Button
    // =========================================================================
    button: {
      'variant:secondary': {
        backgroundColor:
          'light-dark(rgba(5, 54, 89, 0.1), rgba(223, 226, 229, 0.2))',
      },
    },

    // Heading and text component overrides are auto-generated by typography.scale.
    // No manual heading: { ... } or text: { ... } blocks needed.
  },

  // =========================================================================
  // On-media overrides
  // =========================================================================
  // Customize how components look on inverted surfaces (e.g. dark toast on
  // a light page). color-scheme + base token overrides are provided by
  // default; these add component-level adjustments.

  onDark: {
    components: {
      button: {
        'variant:secondary': {
          backgroundColor: 'color-mix(in srgb, white 20%, transparent)',
        },
      },
    },
  },

  onLight: {
    components: {
      button: {
        'variant:secondary': {
          backgroundColor: 'color-mix(in srgb, black 10%, transparent)',
        },
      },
    },
  },

  icons: defaultIconRegistry,
});
