/**
 * XDS Default Theme
 *
 * The reference theme — provides the standard XDS visual language.
 * Uses defineTheme for CSS-based theming (no StyleX build required for consumers).
 *
 * Typography sizing is driven by typography.scale, which auto-generates both
 * the token values (--text-heading-1-size, --text-body-size, etc.) and the
 * component override rules (.xds-heading.level-1 { font-size: ... }).
 *
 * Only non-typography component overrides need to be specified manually.
 */

import {defineTheme} from '@xds/core/theme';
import {defaultIconRegistry} from './icons';

export const defaultTheme = defineTheme({
  name: 'default',

  // Typography: base=14px, ratio=1.2, h4 anchored to base.
  // Generates all heading + text tokens AND component overrides automatically.
  typography: {scale: {base: 14, ratio: 1.2}},

  // Motion: base durations from Ted's proposal (#674), ratio=0.75.
  // Generates: fast-min=130ms, fast=175ms, fast-max=235ms,
  //            medium-min=310ms, medium=410ms, medium-max=545ms.
  motion: {fast: 175, medium: 410, ratio: 0.75},

  // The default theme uses the built-in token defaults from tokens.stylex.ts.
  // No additional token overrides needed.
  tokens: {},

  components: {
    // =========================================================================
    // Button
    // =========================================================================
    button: {
      'variant:secondary': {
        backgroundColor:
          'light-dark(rgba(5, 54, 89, 0.1), rgba(223, 226, 229, 0.2))',
      },
    },

    // Heading and text component overrides are auto-generated by typography.scale.
    // No manual heading: { ... } or text: { ... } blocks needed.
  },

  icons: defaultIconRegistry,
});
