/** @type {import('../docs-types').ComponentDoc} */

export const docs = {
  name: 'Chat',
  group: 'Chat',
  keywords: ['chat', 'message', 'bubble', 'conversation', 'ai', 'assistant', 'thread', 'system-message', 'composer', 'mention', 'trigger', 'typeahead', 'token', 'imperative', 'tokenized-text'],
  theming: {
    targets: [
      {className: 'xds-chat-layout', visualProps: ['density']},
      {className: 'xds-chat-composer', visualProps: ['density']},
      {className: 'xds-chat-composer-input'},
      {className: 'xds-chat-composer-drawer', visualProps: ['collapsed']},
      {className: 'xds-chat-message', visualProps: ['sender']},
      {className: 'xds-chat-message-bubble', visualProps: ['sender', 'variant']},
      {className: 'xds-chat-message-list', visualProps: ['density']},
      {className: 'xds-chat-system-message', visualProps: ['variant']},
      {className: 'xds-chat-message-metadata'},
      {className: 'xds-chat-send-button'},
      {className: 'xds-chat-tokenized-text'},
      {className: 'xds-chat-tool-calls'},
      {className: 'xds-trigger-menu'},
    ],
    vars: [
      {name: '--_chat-composer-radius', description: 'Border radius of the composer body. Inner elements derive their radius concentrically.', default: 'var(--radius-page)', private: true},
      {name: '--_chat-composer-padding', description: 'Padding of the composer body. Used in the concentric radius calculation.', default: 'var(--spacing-3)', private: true},
      {name: '--_button-radius', description: 'Concentric button radius inside the composer.', default: 'max(var(--radius-element), calc(var(--_chat-composer-radius) - var(--_chat-composer-padding)))', private: true, derived: true, formula: 'max(var(--radius-element), calc(var(--_chat-composer-radius) - var(--_chat-composer-padding)))'},
    ],
    derived: [
      {property: 'borderRadius', vars: ['--_chat-composer-radius']},
      {property: 'padding', vars: ['--_chat-composer-padding']},
    ],
  },
  components: [
    {
      name: 'XDSChatMessageList',
      description: 'Presentational message container with density context and infinite scroll support. Provides role="log" with aria-live="polite" for accessibility. A flex spacer pushes messages to the bottom when the list isn\'t full.',
      props: [
        {name: 'children', type: 'ReactNode', description: 'Message elements — typically XDSChatMessage or XDSChatSystemMessage.', required: true},
        {name: 'emptyState', type: 'ReactNode', description: 'Content shown when the list has no messages.'},
        {name: 'scrollToTopAction', type: '() => Promise<void>', description: 'Async action fired when user scrolls to top. Use for loading older messages. Wrapped in useTransition — shows a spinner at the top while pending.'},
        {name: 'density', type: "'compact' | 'balanced' | 'spacious'", description: 'Visual density — flows to child messages via context.', default: "'balanced'"},
      ],
    },
    {
      name: 'XDSChatMessage',
      description: 'Sender context wrapper — handles avatar, name, metadata, and alignment based on sender role.',
      props: [
        {name: 'sender', type: "'user' | 'assistant' | 'system'", description: 'Who sent this message — controls alignment and layout.', required: true},
        {name: 'children', type: 'ReactNode', description: 'Free-form content: bubbles, asset lists, tool calls, images.', required: true},
        {name: 'avatar', type: 'ReactNode', description: 'Avatar element rendered beside the message. Typically XDSAvatar.'},
        {name: 'name', type: 'ReactNode', description: 'Sender name rendered above the message body. Use when the first child is raw content (not a bubble). If the first child is a bubble, put the name on the bubble\'s `name` prop instead.'},
        {name: 'metadata', type: 'ReactNode', description: 'Metadata rendered below the message body. Use when the last child is raw content (not a bubble). If the last child is a bubble, put metadata on the bubble\'s `metadata` prop instead.'},
        {name: 'density', type: "'compact' | 'balanced' | 'spacious'", description: 'Visual density. Inherited from list context if not set.'},
      ],
    },
    {
      name: 'XDSChatMessageBubble',
      description: 'Styled content container — the chat “bubble.” Reads sender from parent XDSChatMessage context to auto-style the background. Use filled for standard messages and ghost when content needs alignment without a visible boundary. Supports name/metadata slots aligned with bubble padding, and multi-bubble grouping via the group prop for consecutive messages from the same sender.',
      props: [
        {name: 'children', type: 'ReactNode', description: 'Bubble content — text, XDSMarkdown, or any ReactNode.', required: true},
        {name: 'variant', type: "'filled' | 'ghost'", description: "Visual variant. 'filled' renders sender-colored background (default). 'ghost' renders transparent background but keeps padding for alignment.", default: "'filled'"},
        {name: 'name', type: 'ReactNode', description: "Sender name rendered above the bubble, aligned with bubble text padding. Use on the first bubble in a message. If the first content is raw (no bubble), use XDSChatMessage's `name` prop instead."},
        {name: 'metadata', type: 'ReactNode', description: "Metadata content rendered below the bubble, aligned with bubble text padding. Use on the last bubble in a message. If the last content is raw (no bubble), use XDSChatMessage's `metadata` prop instead."},
        {name: 'group', type: "'first' | 'middle' | 'last'", description: 'Position within a multi-bubble group. Controls corner radius reduction on the sender side. Leave unset for standalone bubbles (full radius).'},
      ],
    },
    {
      name: 'XDSChatMessageMetadata',
      description: 'Composable metadata row for chat messages. Renders timestamp, footer content, and delivery status in a single row. Direction reverses for user sender. Renders nothing if all props are empty.',
      props: [
        {name: 'timestamp', type: 'ReactNode', description: 'Timestamp content — a string or XDSTimestamp component.'},
        {name: 'footer', type: 'ReactNode', description: 'Footer content — model info, reaction buttons, copy button.'},
        {name: 'status', type: "'sending' | 'sent' | 'delivered' | 'read' | 'error'", description: 'Message delivery status. Shows icon + label.'},
      ],
    },
    {
      name: 'XDSChatSystemMessage',
      description: 'Centered system message for non-sender content like date separators, membership changes, and status notices. It is not a chat bubble — it has no avatar, no alignment, and no sender context. Use the divider variant for temporal breaks and default for inline status updates.',
      props: [
        {name: 'children', type: 'ReactNode', description: 'System message content — a short, factual string like a date, a join/leave notice, or a status change.', required: true},
        {name: 'variant', type: "'default' | 'divider'", description: "Visual variant. 'default' renders centered text. 'divider' adds horizontal lines on each side via XDSDivider — use for date separators and section breaks.", default: "'default'"},
        {name: 'icon', type: 'ReactNode', description: 'Leading icon that reinforces the message type. Wrap in XDSIcon for consistent sizing. Use for membership changes, encryption notices, or AI activity.'},
      ],
    },
    {
      name: 'XDSChatComposer',
      description: 'Layout shell for a chat composer. Arranges named slots (drawer, header, input, footer, send) with page-radius container, hover/focus shadows, and concentric inner radius for child elements.',
      props: [
        {name: 'onSubmit', type: '(value: string) => void', description: 'Called when the user submits a message.', required: true},
        {name: 'onStop', type: '() => void', description: 'Called when the user requests to stop generation.'},
        {name: 'isStreaming', type: 'boolean', description: 'Whether the assistant is currently streaming.', default: 'false'},
        {name: 'value', type: 'string', description: 'Controlled input value.'},
        {name: 'onChange', type: '(value: string) => void', description: 'Change handler for controlled mode.'},
        {name: 'placeholder', type: 'string', description: 'Placeholder text shown when the input is empty.', default: "'Type a message\u2026'"},
        {name: 'isDisabled', type: 'boolean', description: 'Disables the composer.', default: 'false'},
        {name: 'density', type: "'compact' | 'balanced' | 'spacious'", description: 'Visual density.', default: "'balanced'"},
        {name: 'drawer', type: 'ReactNode', description: 'Slot: collapsible drawer above the input — attachments, context chips, etc. Use XDSChatComposerDrawer.'},
        {name: 'headerActions', type: 'ReactNode', description: 'Slot: left-aligned header actions (attach, mention buttons). Use icon-only size="sm" buttons.'},
        {name: 'headerContext', type: 'ReactNode', description: 'Slot: right-aligned contextual info in the header (context window usage, XDSProgressBar, supporting text).'},
        {name: 'input', type: 'ReactNode', description: 'Slot: custom input element. Replaces the default textarea. Use XDSChatComposerInput for trigger menus.'},
        {name: 'footerActions', type: 'ReactNode', description: 'Slot: left-aligned footer actions (model selector, etc).'},
        {name: 'sendActions', type: 'ReactNode', description: 'Slot: actions to the left of the send button.'},
        {name: 'sendButton', type: 'ReactNode', description: 'Slot: custom send button. Replaces the default send/stop button.'},
        {name: 'status', type: "{ type: 'error' | 'warning'; message?: string }", description: 'Status message rendered below (or above) the composer.'},
        {name: 'statusPosition', type: "'top' | 'bottom'", description: 'Where to render the status.', default: "'bottom'"},
      ],
    },
    {
      name: 'XDSChatComposerInput',
      description: 'Rich text input for the chat composer. Supports trigger menus (type @ or / to open a typeahead), inline tokens rendered as badges, message history recall with ArrowUp/Down, and paste/drop file handling. Pass it to XDSChatComposer\'s input slot when you need more than a plain textarea.',
      props: [
        {name: 'ref', type: 'React.Ref<XDSChatComposerInputHandle>', description: 'Imperative handle for programmatic control — insertToken, insertText, focus, and getValue.'},
        {name: 'value', type: 'string', description: 'Controlled input value. Pair with onChange for two-way binding.'},
        {name: 'onChange', type: '(value: string) => void', description: 'Called when the input value changes. The serialized string includes token placeholders.'},
        {name: 'placeholder', type: 'string', description: 'Placeholder text shown when the input is empty.', default: "'Type a message\u2026'"},
        {name: 'maxRows', type: 'number', description: 'Maximum visible rows before the input scrolls. Use a lower value in compact layouts.', default: '8'},
        {name: 'triggers', type: 'XDSChatComposerTrigger[]', description: 'Trigger definitions for typeahead menus. Each trigger specifies a character (@ or /), a search source, and an onSelect handler that returns the token to insert.'},
        {name: 'debounceMs', type: 'number', description: 'Debounce delay for async search sources to avoid excessive network requests.', default: '150'},
        {name: 'hasHistory', type: 'boolean', description: 'Enable ArrowUp/Down to recall previously submitted messages.', default: 'true'},
        {name: 'label', type: 'string', description: 'Accessible label announced by screen readers.', default: "'Message input'"},
        {name: 'isDisabled', type: 'boolean', description: 'Disables the input. Use during streaming or when a prerequisite is unmet.', default: 'false'},
        {name: 'onPaste', type: '(event, text) => void', description: 'Called when text is pasted. Use to intercept or transform pasted content.'},
        {name: 'onFiles', type: '(files: File[]) => void', description: 'Called when files are pasted or dropped onto the input. Use to handle attachments.'},
        {name: 'onSubmit', type: '(value: string) => void', description: 'Called when the user presses Enter without Shift. The serialized value includes token placeholders.'},
      ],
    },
    {
      name: 'XDSChatComposerDrawer',
      description: 'Collapsible drawer panel that sits above the chat input inside XDSChatComposer. Pass it to the composer\'s `drawer` slot to show attachments, context chips, or any supplementary content. When `count` is provided the drawer gains a collapse toggle — collapsed state shows a badge and label, expanded state shows all children.',
      props: [
        {name: 'children', type: 'ReactNode', description: 'Content to render inside the drawer — tokens, chips, previews, or any React elements.', required: true},
        {name: 'count', type: 'number', description: 'Total item count shown in the collapsed badge. When provided, the drawer gains a collapse/expand toggle.'},
        {name: 'label', type: 'string', description: 'Label shown next to the count in collapsed state.', default: "'Items'"},
        {name: 'isCollapsed', type: 'boolean', description: 'Controlled collapsed state. Use with `onCollapsedChange` for external control.'},
        {name: 'defaultIsCollapsed', type: 'boolean', description: 'Initial collapsed state for uncontrolled usage.', default: 'false'},
        {name: 'onCollapsedChange', type: '(isCollapsed: boolean) => void', description: 'Callback fired when the user toggles the drawer.'},
      ],
    },
    {
      name: 'XDSChatSendButton',
      description: 'Circular send/stop toggle button for the chat composer. Place it inside XDSChatComposer where it reads context automatically — no wiring needed. When streaming starts, the button switches from a primary send icon to a secondary stop icon. Override any context value via props for standalone or custom usage.',
      props: [
        {name: 'isStreaming', type: 'boolean', description: 'Whether the assistant is currently streaming. Defaults to context value.'},
        {name: 'isDisabled', type: 'boolean', description: 'Whether the send button is disabled. Defaults to !canSend from context.'},
        {name: 'onSend', type: '() => void', description: 'Called when the user clicks send. Defaults to context onSubmit.'},
        {name: 'onStop', type: '() => void', description: 'Called when the user clicks stop during streaming. Defaults to context onStop.'},
        {name: 'sendIcon', type: 'ReactNode', description: 'Custom icon for the send state. Defaults to arrowUp from icon registry.'},
        {name: 'stopIcon', type: 'ReactNode', description: 'Custom icon for the stop state. Defaults to stop from icon registry.'},
        {name: 'size', type: "'sm' | 'md'", description: 'Button size.', default: "'md'"},
        {name: 'xstyle', type: 'StyleXStyles', description: 'Additional StyleX styles.'},
      ],
    },
    {
      name: 'XDSChatToolCalls',
      description: 'Displays tool/function call invocations from an LLM response. Accepts a `calls` array matching the shape LLM APIs return. Single call renders inline; multiple calls get a collapsible summary with the latest call visible at the surface.',
      props: [
        {name: 'calls', type: 'XDSChatToolCallItem[]', description: 'Array of tool call data. Each item has name, status, target, duration, node, additions, deletions, stats, resultDetail.', required: true},
        {name: 'label', type: 'string', description: 'Custom summary label for groups. Auto-generated from count if omitted.'},
        {name: 'isExpanded', type: 'boolean', description: 'Controlled expanded state.'},
        {name: 'defaultIsExpanded', type: 'boolean', description: 'Default expanded state (uncontrolled).', default: 'false'},
        {name: 'onExpandedChange', type: '(isExpanded: boolean) => void', description: 'Callback when expanded state changes.'},
      ],
    },
    {
      name: 'XDSChatTokenizedText',
      description: 'Renders a text string with token patterns replaced by inline XDSBadge components. Wrap any message body inside XDSChatMessageBubble to turn raw @mentions, #tags, or /commands into styled badges. When no tokens match or none are provided, the text renders as-is — so you can use ChatTokenizedText unconditionally on every message.',
      props: [
        {name: 'children', type: 'string', description: 'The plain text message containing serialized token values. Patterns matching a token\'s value are replaced with badge components inline.', required: true},
        {name: 'tokens', type: 'XDSChatComposerToken[]', description: 'Token definitions — same type returned by trigger onSelect. Each token has a value (the string to match), label (display text), and optional variant and icon. Uses the same type as the composer input, so token definitions work for both input and display.'},
      ],
    },
    {
      name: 'XDSChatComposerTokenElement',
      description: 'Renders a single token chip outside the contentEditable input. Wraps a badge config or custom render function in the correct data-xds-token span so the token serializes properly and stays visually consistent with tokens inside the composer.',
      props: [
        {name: 'token', type: 'XDSChatComposerToken', description: 'The token to render. Pass a badge config ({ value, label, variant?, icon? }) for the common case, or a custom render ({ value, render }) for full control.', required: true},
      ],
    },
  ],
  usage: {
    description: 'XDSChatMessageList is the scrollable container for chat messages. It renders children in a flex column with role="log" for accessibility, provides density context to child messages, and supports infinite scroll for loading older messages. Use it inside XDSChatLayout for full-page chat with auto-scroll and composer docking, or standalone for embedded message panels.',
    bestPractices: [
      { guidance: true, description: 'Compose messages using MessageList > Message > Bubble for consistent sender-aware styling and density.' },
      { guidance: true, description: 'Set the density prop to control spacing globally — compact for sidebars, balanced for most views, spacious for long-form reading. Individual messages can override.' },
      { guidance: true, description: 'Use the group prop on bubbles (first, middle, last) when a single sender sends multiple consecutive messages — it tightens corner radius to visually connect them.' },
      { guidance: true, description: 'Use XDSChatSystemMessage with variant="divider" for date separators and default for inline status notices like joins, leaves, or topic changes.' },
      { guidance: true, description: 'Put name on the first bubble and metadata on the last bubble in a message so they align with the bubble\'s inline padding.' },
      { guidance: true, description: 'Provide an emptyState prop so new users see a clear prompt to start a conversation instead of a blank screen.' },
      { guidance: true, description: 'Use the ghost bubble variant for AI-style responses that show rich content like code blocks or markdown without a visible boundary.' },
      { guidance: false, description: 'Don\'t use XDSChatSystemMessage for sender content — it has no avatar, alignment, or bubble. Use XDSChatMessage with a sender role instead.' },
      { guidance: false, description: 'Don\'t put long or multi-line content in a system message — keep it to a single short sentence. If you need more, use a bubble or a card.' },
      { guidance: false, description: 'Don\'t nest XDSChatMessage inside another XDSChatMessage — each message is a standalone article element with its own sender context.' },
      { guidance: false, description: 'Don\'t apply a fixed height directly on the message list — wrap it in a sized container and let the list fill with flex: 1.' },
      { guidance: false, description: 'Don\'t mix filled and ghost bubble variants within the same sender\'s messages — pick one style per side and use it consistently.' },
      { guidance: false, description: 'Don\'t place metadata or names on both the bubble and the message wrapper — pick one based on whether the content has a bubble boundary.' },
],
    anatomy: [
      { name: 'Message area', required: true, description: 'Scrollable region for messages. Renders children (typically XDSChatMessageList) in a flex column that pushes content to the bottom when the list is short.' },
      { name: 'Frosted glass dock', required: true, description: 'Sticky or fixed container at the bottom with a backdrop-blur layer. Houses the scroll button and composer.' },
      { name: 'Scroll-to-bottom button', required: false, description: 'Appears when the user scrolls up or new messages arrive. Defaults to XDSChatLayoutScrollButton; pass null to hide or a custom element to override.' },
      { name: 'Composer', required: true, description: 'The input area for sending messages, typically XDSChatComposer. Docked at the bottom inside the frosted glass layer.' },
      { name: 'Empty state', required: false, description: 'Centered placeholder shown when no messages exist. Use XDSEmptyState for a consistent look.' },
      { name: 'Avatar', required: false, description: 'A sender avatar rendered beside the message. Typically XDSAvatar with size="small". Hidden for system messages.' },
      { name: 'Name', required: false, description: 'Sender name above the message body. Place on the bubble when using bubbles, or on the message wrapper for raw content.' },
      { name: 'Content', required: true, description: 'The message body — one or more XDSChatMessageBubble elements, or any free-form ReactNode like images or tool calls.' },
      { name: 'Metadata', required: false, description: 'Timestamp, delivery status, and footer actions below the message. Place on the last bubble or on the message wrapper.' },
    ],
  },
};

// Append XDSChatLayout and XDSChatLayoutScrollButton to all doc variants
const chatLayoutComponent = {
  name: 'XDSChatLayout',
  description: 'Layout shell for full chat interfaces. Messages flow in normal page flow, composer is fixed to the bottom with a frosted glass dock. Adapts density (compact/balanced/spacious) automatically via container width observation. Includes built-in auto-scroll, a "New messages" scroll-to-bottom button, and a frosted glass blur layer behind the composer. By default the layout root is the scroll container; pass scrollRef to delegate scrolling to a parent element or the document body.',
  props: [
    {name: 'children', type: 'ReactNode', description: 'Message content — typically XDSChatMessageList. Flows naturally in the page and scrolls with the container.', required: true},
    {name: 'composer', type: 'ReactNode', description: 'Composer element — typically XDSChatComposer. Fixed to the bottom with a frosted glass dock.', required: true},
    {name: 'emptyState', type: 'ReactNode', description: 'Content shown when children is empty. Centered vertically in the message area.'},
    {name: 'scrollButton', type: 'ReactNode | null', description: 'Scroll-to-bottom button rendered above the composer. Defaults to XDSChatLayoutScrollButton with auto-scroll integration. Pass null to hide.'},
    {name: 'scrollRef', type: 'React.RefObject<HTMLElement | null>', description: 'External scroll container ref. When provided, auto-scroll and scroll-to-bottom target this element instead of the layout root. Use when the chat is embedded in a page where a parent element or the document body scrolls.'},
  ],
};
docs.components.push(chatLayoutComponent);

const chatLayoutScrollButtonComponent = {
  name: 'XDSChatLayoutScrollButton',
  description: 'Floating scroll-to-bottom button that appears when the user scrolls away from the latest messages. It fades in as a compact icon button and expands to show a label when new messages arrive. XDSChatLayout renders this by default — pass a custom element to the scrollButton prop to override, or null to hide it entirely.',
  props: [
    {name: 'isVisible', type: 'boolean', description: 'Whether the button is visible. Bind to a scroll-position check so the button only appears when the user has scrolled up.', required: true},
    {name: 'label', type: 'string', description: 'Optional label that expands the button (e.g. "New messages"). Use to signal unread content below the fold.'},
    {name: 'onClick', type: '() => void', description: 'Click handler — typically scrolls to bottom and dismisses the new message indicator.', required: true},
  ],
};
docs.components.push(chatLayoutScrollButtonComponent);

/** @type {import('../docs-types').TranslationDoc} */
export const docsZh = {
  usage: {
    description: 'XDSChatMessageList 是聊天消息的可滚动容器。它以 flex 列的形式渲染子元素，使用 role="log" 确保无障碍性，通过上下文向子消息提供密度设置，并支持无限滚动以加载更早的消息。在 XDSChatLayout 内使用它可获得全页聊天体验（自动滚动和编辑器停靠），也可独立用于嵌入式消息面板。',
    bestPractices: [
      { guidance: true, description: '使用 MessageList > Message > Bubble 组合来获得一致的发送者感知样式和密度。' },
      { guidance: true, description: '设置 density 属性来全局控制间距 — compact 用于侧边栏，balanced 用于大多数视图，spacious 用于长篇阅读。' },
      { guidance: true, description: '当同一发送者发送多条连续消息时，使用气泡的 group 属性（first、middle、last）来视觉上连接相关消息。' },
      { guidance: true, description: '使用 XDSChatSystemMessage 的 variant="divider" 作为日期分隔线，使用 default 作为内联状态通知。' },
      { guidance: true, description: '将 name 放在第一个气泡上，metadata 放在最后一个气泡上，使其与气泡的内边距对齐。' },
      { guidance: true, description: '提供 emptyState 属性，让新用户看到开始对话的提示，而不是空白屏幕。' },
      { guidance: true, description: '使用 ghost 气泡变体显示代码块或 Markdown 等富内容，无需可见边界。' },
      { guidance: false, description: '不要将 XDSChatSystemMessage 用于发送者内容 — 它没有头像、对齐或气泡。请使用带有发送者角色的 XDSChatMessage。' },
      { guidance: false, description: '不要在系统消息中放置冗长或多行内容 — 保持一句简短的话。如需更多内容，请使用气泡或卡片。' },
      { guidance: false, description: '不要将 XDSChatMessage 嵌套在另一个 XDSChatMessage 内 — 每条消息都是独立的 article 元素。' },
      { guidance: false, description: '不要直接在消息列表上应用固定高度 — 将其包裹在有尺寸的容器中，让列表以 flex: 1 填充。' },
      { guidance: false, description: '不要在同一发送者的消息中混用 filled 和 ghost 气泡变体 — 每一侧选择一种样式并保持一致。' },
      { guidance: false, description: '不要同时在气泡和消息包装器上放置 metadata 或 name — 根据内容是否有气泡边界来选择。' },
    ],
    anatomy: [
      { name: 'Message area', required: true, description: 'Scrollable region for messages. Renders children (typically XDSChatMessageList) in a flex column that pushes content to the bottom when the list is short.' },
      { name: 'Frosted glass dock', required: true, description: 'Sticky or fixed container at the bottom with a backdrop-blur layer. Houses the scroll button and composer.' },
      { name: 'Scroll-to-bottom button', required: false, description: 'Appears when the user scrolls up or new messages arrive. Defaults to XDSChatLayoutScrollButton; pass null to hide or a custom element to override.' },
      { name: 'Composer', required: true, description: 'The input area for sending messages, typically XDSChatComposer. Docked at the bottom inside the frosted glass layer.' },
      { name: 'Empty state', required: false, description: 'Centered placeholder shown when no messages exist. Use XDSEmptyState for a consistent look.' },
    ],
  },
  components: [
    {
      name: 'XDSChatMessageList',
      description: '消息展示容器，支持密度上下文和无限滚动。自动滚动由 XDSChatLayout 管理。',
      propDescriptions: {
        children: '消息元素，通常是 XDSChatMessage 或 XDSChatSystemMessage。',
        emptyState: '列表无消息时显示的内容。',
        scrollToTopAction: '用户滚动到顶部时触发的异步操作。用于加载更早的消息。',
        density: '视觉密度，通过上下文传递给子消息。',
      },
    },
    {
      name: 'XDSChatMessage',
      description: '发送者上下文包装器，根据发送者角色处理头像、名称、元数据和对齐方式。',
      propDescriptions: {
        sender: '消息发送者，控制对齐和布局。',
        children: '自由内容：气泡、资源列表、工具调用、图片。',
        avatar: '消息旁边渲染的头像元素。通常是 XDSAvatar。',
        name: '消息正文上方渲染的发送者名称。当第一个子元素不是气泡时使用。',
        metadata: '消息正文下方渲染的元数据。当最后一个子元素不是气泡时使用。',
        density: '视觉密度。未设置时从列表上下文继承。',
      },
    },
    {
      name: 'XDSChatMessageBubble',
      description: '样式化的气泡容器，从父上下文读取发送者信息进行自动样式化。支持 name/metadata 插槽、多气泡分组和透明变体。',
      propDescriptions: {
        children: '气泡内容：文本、XDSMarkdown 或任何 ReactNode。',
        variant: "视觉变体。'filled' 渲染发送者颜色背景，'ghost' 渲染透明背景但保持填充对齐。",
        name: '气泡上方渲染的发送者名称，与气泡文本内边距对齐。用于消息中的第一个气泡。',
        metadata: '气泡下方渲染的元数据内容，与气泡文本内边距对齐。用于消息中的最后一个气泡。',
        group: '多气泡组中的位置。控制发送者侧的圆角缩减。',
      },
    },
    {
      name: 'XDSChatMessageMetadata',
      description: '可组合的消息元数据行。渲染时间戳、页脚内容和发送状态。用户消息方向反转。',
      propDescriptions: {timestamp: '时间戳内容 — 字符串或 XDSTimestamp 组件。', footer: '页脚内容 — 模型信息、反应按钮、复制按钮。', status: '消息发送状态。显示图标和标签。'},
    },
    {
      name: 'XDSChatSystemMessage',
      description: '居中的系统消息，用于日期分隔、成员变更和状态通知等非发送者内容。没有头像、对齐或气泡。使用 divider 变体做时间分隔，default 做内联状态更新。',
      propDescriptions: {children: '系统消息内容 — 简短的事实性文本，如日期、加入/离开通知或状态变更。', variant: "视觉变体。'default' 渲染居中文本。'divider' 通过 XDSDivider 在两侧添加水平线 — 用于日期分隔和段落分隔。", icon: '增强消息类型辨识度的前置图标。使用 XDSIcon 包裹以获得一致的尺寸。'},
    },
    {
      name: 'XDSChatComposer',
      description: '聊天编写器布局外壳。排列命名插槽（附件、标题栏、输入、页脚、发送），带有页面圆角容器和同心内圆角。',
      propDescriptions: {
        onSubmit: '用户提交消息时调用。',
        onStop: '用户请求停止生成时调用。',
        isStreaming: '助手是否正在流式输出。',
        value: '受控输入值。',
        onChange: '受控模式的输入值变更时调用。序列化字符串包含标记占位符。',
        placeholder: '输入为空时显示的占位文本。',
        isDisabled: '禁用编写器。',
        density: '视觉密度。',
        drawer: '插槽：输入上方的可折叠抽屉——附件、上下文标签等。使用 XDSChatComposerDrawer。',
        headerActions: '插槽：标题左侧操作按钮（附件、提及按钮）。使用仅图标 size="sm" 按钮。',
        headerContext: '插槽：标题右侧上下文信息（上下文窗口使用情况、XDSProgressBar、辅助文本）。',
        input: '插槽：自定义输入元素。替换默认文本区域。使用 XDSChatComposerInput 实现触发菜单。',
        footerActions: '插槽：左对齐的页脚操作（模型选择器等）。',
        sendActions: '插槽：发送按钮左侧的操作。',
        sendButton: '插槽：自定义发送按钮。替换默认的发送/停止按钮。',
        status: '编写器下方（或上方）的状态消息。',
        statusPosition: '状态渲染位置。',
      },
    },
    {
      name: 'XDSChatComposerInput',
      description:
        '聊天编写器的富文本输入。支持触发菜单（输入 @ 或 / 打开 typeahead）、内联标记徽章、ArrowUp/Down 消息历史回溯、粘贴/拖放文件处理。当需要普通文本区域以外的功能时，传入 XDSChatComposer 的 input 插槽。',
      propDescriptions: {
        ref: '命令式句柄，用于编程式控制 — insertToken、insertText、focus 和 getValue。',
        value: '受控输入值。与 onChange 配对实现双向绑定。',
        onChange: '输入值变更时调用。序列化字符串包含标记占位符。',
        placeholder: '输入为空时显示的占位文本。',
        maxRows: '滚动前的最大可见行数。紧凑布局中使用较小值。',
        triggers: '菜单的触发定义。每个触发器指定字符（@ 或 /）、搜索源和返回要插入标记的 onSelect 处理器。',
        debounceMs: '异步搜索源的去抖动延迟，避免过多网络请求。',
        hasHistory: '启用 ArrowUp/Down 回溯之前提交的消息。',
        label: '屏幕阅读器播报的无障碍标签。',
        isDisabled: '禁用输入。在流式输出期间或前置条件未满足时使用。',
        onPaste: '粘贴文本时调用。用于拦截或转换粘贴内容。',
        onFiles: '粘贴或拖放文件到输入时调用。用于处理附件。',
        onSubmit: '用户不按 Shift 按 Enter 时调用。序列化值包含标记占位符。',
      },
    },
    {
      name: 'XDSChatComposerDrawer',
      description: '位于聊天输入上方的可折叠抽屉面板。传入 XDSChatComposer 的 `drawer` 插槽，用于显示附件、上下文标签或预览内容。提供 `count` 时启用折叠切换。',
      propDescriptions: {children: '抽屉内渲染的内容——标记、标签、预览或任何 React 元素。', count: '折叠徽章中显示的总数。提供时，抽屉获得折叠/展开切换。', label: '折叠状态下显示在数量旁边的标签。', isCollapsed: '受控折叠状态。与 onCollapsedChange 一起使用。', defaultIsCollapsed: '非受控模式的初始折叠状态。', onCollapsedChange: '用户切换抽屉时触发的回调。'},
    },
    {
      name: 'XDSChatSendButton',
      description:
        '编写器的圆形发送/停止切换按钮。默认从 XDSChatComposerContext 读取状态，在 XDSChatComposer 内自动工作。所有上下文值均可通过 props 覆盖以用于独立使用。',
      propDescriptions: {
        isStreaming: '助手是否正在流式响应。默认使用上下文值。',
        isDisabled: '发送按钮是否禁用。默认使用上下文的 !canSend。',
        onSend: '用户点击发送时调用。默认使用上下文的 onSubmit。',
        onStop: '流式响应期间用户点击停止时调用。默认使用上下文的 onStop。',
        sendIcon: '发送状态的自定义图标。默认使用图标注册表的 arrowUp。',
        stopIcon: '停止状态的自定义图标。默认使用图标注册表的 stop。',
        size: '按钮大小。',
        xstyle: '额外的 StyleX 样式。',
      },
    },
    {
      name: 'XDSChatToolCalls',
      description:
        '显示 LLM 响应中的工具/函数调用。接受与 LLM API 返回形状匹配的 calls 数组。单个调用内联渲染；多个调用显示可折叠摘要。',
      propDescriptions: {
        calls:
          '工具调用数据数组。每项包含 name、status、target、duration、node、additions、deletions、stats、resultDetail。',
        label: '组的自定义摘要标签。省略时从数量自动生成。',
        isExpanded: '受控展开状态。',
        defaultIsExpanded: '默认展开状态（非受控）。',
        onExpandedChange: '展开状态变更时的回调。',
      },
    },
    {
      name: 'XDSChatTokenizedText',
      description:
        '渲染带有标记模式的文本，将匹配的模式替换为内联 XDSBadge 组件。在 XDSChatMessageBubble 内使用，将 @提及、#标签或 /命令显示为样式化徽章。未提供标记时以纯文本渲染，因此可以无条件使用。',
      propDescriptions: {children: '包含序列化标记值的纯文本消息。匹配标记值的模式将被替换为内联徽章组件。', tokens: '标记定义 — 与触发器 onSelect 返回的类型相同。每个包含 value（匹配字符串）、label（显示文本）以及可选的 variant 和 icon。'},
    },
    {
      name: 'XDSChatComposerTokenElement',
      description: '在 contentEditable 外部渲染标记芯片。',
      propDescriptions: {token: '徽章配置或自定义渲染。'},
    },
    {
      name: 'XDSChatLayout',
      description: '完整聊天界面的布局外壳。消息在页面中自然流动，编写器固定在底部，带有毛玻璃效果。通过容器宽度自动适配密度。',
      propDescriptions: {
        children: '消息内容 — 通常是 XDSChatMessageList。在页面中自然流动。',
        composer: '编写器元素 — 通常是 XDSChatComposer。固定在底部，带有毛玻璃底座。',
        emptyState: '子元素为空时显示的内容。',
        scrollButton: '编写器上方的滚动到底部按钮。默认使用 XDSChatLayoutScrollButton。传入 null 隐藏。',
        scrollRef: '外部滚动容器引用。提供时，自动滚动和滚动到底部将目标指向此元素。',
      },
    },
    {
      name: 'XDSChatLayoutScrollButton',
      description: '可组合的滚动到底部按钮。可见时淡入，提供标签时展开。',
      propDescriptions: {isVisible: '按钮是否可见。', label: '可选标签 — 展开按钮（如"新消息"）。', onClick: '点击处理器。'},
    },
  ],
};

/** @type {import('../docs-types').TranslationDoc} */
export const docsDense = {
  description: 'AI chat components. Layout (MessageList>Message>Bubble+SystemMessage) + Composer (shell w/ slots, ContentEditable input w/ trigger menus, tokens, msg history, attachments)',
  usage: {
    description: 'XDSChatMessageList: scrollable msg container w/ role="log", density context, infinite scroll. Use inside XDSChatLayout for full-page chat or standalone for embedded panels.',
    bestPractices: [
      { guidance: true, description: 'MessageList > Message > Bubble for sender-aware styling.' },
      { guidance: true, description: 'Density prop controls global spacing — compact for sidebars, balanced default, spacious for reading.' },
      { guidance: true, description: 'Group prop on bubbles (first/middle/last) for consecutive same-sender messages — tightens corner radius.' },
      { guidance: true, description: 'SystemMessage: divider variant for date breaks, default for status notices.' },
      { guidance: true, description: 'Name on first bubble, metadata on last — aligns with bubble inline padding.' },
      { guidance: true, description: 'Provide emptyState so new users see a prompt, not a blank screen.' },
      { guidance: true, description: 'Ghost bubble variant for rich AI content like code/markdown without visible boundary.' },
      { guidance: false, description: 'SystemMessage for sender content — no avatar/alignment/bubble. Use ChatMessage instead.' },
      { guidance: false, description: 'Long/multi-line system messages — keep to a single short sentence.' },
      { guidance: false, description: 'Nesting XDSChatMessage inside another — each is a standalone article.' },
      { guidance: false, description: 'Fixed height on message list directly — wrap in a sized container, let flex: 1 fill.' },
      { guidance: false, description: 'Mix filled and ghost variants in same sender\'s messages — pick one style per side.' },
      { guidance: false, description: 'Metadata/names on both bubble and wrapper — pick one.' },
],
  },
  components: [
    {
      name: 'XDSChatMessageList',
      description: 'presentational msg container w/ density context + infinite scroll; auto-scroll owned by XDSChatLayout',
      propDescriptions: {
        children: 'msg elements (XDSChatMessage or XDSChatSystemMessage)',
        emptyState: 'content when no msgs',
        scrollToTopAction: 'async action at scroll top; load older msgs',
        density: 'visual density; flows to children via context',
      },
    },
    {
      name: 'XDSChatMessage',
      description: 'sender context wrapper; handles avatar+name+metadata+alignment by sender role',
      propDescriptions: {
        sender: 'who sent; controls alignment+layout',
        children: 'free-form: bubbles, assets, tool calls, images',
        avatar: 'avatar element beside msg; typically XDSAvatar',
        name: 'sender name above body; use when first child is raw (not bubble)',
        metadata: 'metadata below body; use when last child is raw (not bubble)',
        density: 'visual density; inherited from list context if unset',
      },
    },
    {
      name: 'XDSChatMessageBubble',
      description: 'styled bubble container; reads sender from context; supports name/metadata slots, group corners, ghost variant',
      propDescriptions: {
        children: 'bubble content: text, XDSMarkdown, any ReactNode',
        variant: "filled (sender bg) or ghost (transparent, keeps padding)",
        name: 'sender name above bubble, aligned w/ bubble padding',
        metadata: 'metadata below bubble, aligned w/ bubble padding',
        group: "position in multi-bubble group; controls corner radius reduction",
      },
    },
    {
      name: 'XDSChatMessageMetadata',
      description: 'composable metadata row; renders timestamp · footer · status; reverses for user sender',
      propDescriptions: {
        timestamp: 'timestamp content; string or XDSTimestamp',
        footer: 'footer content; model info, reaction btns, copy btn',
        status: 'delivery status; shows icon+label',
      },
    },
    {
      name: 'XDSChatSystemMessage',
      description: 'centered non-sender msg; divider variant for date breaks, default for status notices; supports leading icon',
      propDescriptions: {
        children: 'short factual text: date, join/leave, status change',
        variant: "default=centered text, divider=horizontal lines via XDSDivider for date/section breaks",
        icon: 'leading icon reinforcing msg type; wrap in XDSIcon',
      },
    },
    {
      name: 'XDSChatComposer',
      description: 'composer layout shell; named slots (drawer/header/input/footer/send) w/ page-radius + concentric inner radius',
      propDescriptions: {
        onSubmit: 'submit msg handler',
        onStop: 'stop generation handler',
        isStreaming: 'assistant streaming state',
        value: 'controlled input value',
        onChange: 'controlled change handler',
        placeholder: 'placeholder when empty',
        isDisabled: 'disabled; use during streaming or unmet prereqs',
        density: 'visual density',
        drawer: 'slot: collapsible drawer above input — attachments, context chips, etc.; use XDSChatComposerDrawer',
        headerActions: 'slot: left header actions (attach, mention); icon-only sm buttons',
        headerContext: 'slot: right header context info (window usage, XDSProgressBar, text)',
        input: 'slot: custom input; replaces default textarea; use XDSChatComposerInput for triggers',
        footerActions: 'slot: left footer actions (model selector etc)',
        sendActions: 'slot: actions left of send btn',
        sendButton: 'slot: custom send btn; replaces default',
        status: 'status msg below/above composer',
        statusPosition: 'status render position',
      },
    },
    {
      name: 'XDSChatComposerInput',
      description: 'rich input for composer; trigger menus (@/commands), inline tokens, msg history, paste/drop files. Use in XDSChatComposer input slot when you need more than plain textarea.',
      propDescriptions: {
        ref: 'imperative handle (insertToken/insertText/focus/getValue)',
        value: 'controlled value; pair w/ onChange for two-way binding',
        onChange: 'value change handler; serialized string includes token placeholders',
        placeholder: 'placeholder when empty',
        maxRows: 'max visible rows before scroll; lower for compact layouts',
        triggers: 'typeahead trigger defs; character(@/)+searchSource+onSelect returning token',
        debounceMs: 'debounce for async search to avoid excess requests',
        hasHistory: 'ArrowUp/Down to recall previous submissions',
        label: 'a11y label for screen readers',
        isDisabled: 'disabled; use during streaming or unmet prereqs',
        onPaste: 'paste handler; intercept/transform pasted content',
        onFiles: 'file paste/drop handler; use for attachments',
        onSubmit: 'Enter w/o Shift handler; serialized value includes token placeholders',
      },
    },
    {
      name: 'XDSChatComposerDrawer',
      description: 'collapsible drawer above chat input; pass to composer `drawer` slot for attachments, context chips, previews. `count` enables collapse toggle',
      propDescriptions: {
        children: 'drawer content — tokens, chips, previews, any React elements',
        count: 'total count for collapsed badge; enables collapse/expand toggle',
        label: 'collapsed label next to count badge',
        isCollapsed: 'controlled collapsed state',
        defaultIsCollapsed: 'initial collapsed state (uncontrolled)',
        onCollapsedChange: 'callback on collapse toggle',
      },
    },
    {
      name: 'XDSChatSendButton',
      description: 'circular send/stop toggle btn for composer; reads XDSChatComposerContext; all context vals overridable via props',
      propDescriptions: {
        isStreaming: 'streaming state; defaults to context',
        isDisabled: 'disabled; defaults to !canSend from context',
        onSend: 'send click handler; defaults to context onSubmit',
        onStop: 'stop click handler; defaults to context onStop',
        sendIcon: 'custom send icon; default arrowUp from registry',
        stopIcon: 'custom stop icon; default stop from registry',
        size: 'btn size',
        xstyle: 'additional StyleX styles',
      },
    },
    {
      name: 'XDSChatToolCalls',
      description: 'tool/function call display from LLM response; single=inline, multiple=collapsible summary',
      propDescriptions: {
        calls: 'tool call data array; name+status+target+duration+node+additions+deletions+resultDetail',
        label: 'custom summary label; auto from count if omitted',
        isExpanded: 'controlled expanded state',
        defaultIsExpanded: 'default expanded state (uncontrolled)',
        onExpandedChange: 'expanded state change callback',
      },
    },
    {
      name: 'XDSChatTokenizedText',
      description: 'renders text w/ token patterns replaced by inline badges; use in bubble for @mentions, #tags, /commands; degrades to plain text when no tokens match',
      propDescriptions: {
        children: 'plain text msg w/ serialized token values; matching patterns become inline badges',
        tokens: 'token defs (same type as composer input): value+label+variant+icon',
      },
    },
    {
      name: 'XDSChatComposerTokenElement',
      description: 'token chip outside contentEditable; badge config or custom render in data-xds-token span',
      propDescriptions: {token: 'badge config or custom render'},
    },
    {
      name: 'XDSChatLayout',
      description: 'layout shell for full chat; msgs in page flow, composer fixed bottom w/ frosted glass dock; auto density via container width; scrollRef delegates to parent/body',
      propDescriptions: {
        children: 'msg content; typically XDSChatMessageList',
        composer: 'composer element; typically XDSChatComposer; fixed bottom w/ frosted glass',
        emptyState: 'content when children empty',
        scrollButton: 'scroll-to-bottom btn; defaults to XDSChatLayoutScrollButton; pass null to hide',
        scrollRef: 'external scroll container ref; targets parent/body instead of layout root',
      },
    },
    {
      name: 'XDSChatLayoutScrollButton',
      description: 'floating scroll-to-bottom btn; fades in when scrolled up, expands w/ label for new msgs. Default in XDSChatLayout; override via scrollButton prop.',
      propDescriptions: {
        isVisible: 'btn visibility — bind to scroll-position check',
        label: 'optional label; expands btn (e.g. "New messages")',
        onClick: 'click handler',
      },
    },
  ],
};
