/** @type {import('../docs-types').ComponentDoc} */

export const docs = {
  name: 'Chat',
  group: 'Chat',
  keywords: ['chat', 'message', 'bubble', 'conversation', 'ai', 'assistant', 'thread', 'system-message', 'composer', 'mention', 'trigger', 'typeahead', 'token', 'imperative', 'tokenized-text'],
  theming: {
    targets: [
      {className: 'xds-chat-layout', visualProps: ['density']},
      {className: 'xds-chat-composer', visualProps: ['density']},
      {className: 'xds-chat-composer-input'},
      {className: 'xds-chat-composer-drawer', visualProps: ['collapsed']},
      {className: 'xds-chat-message', visualProps: ['sender']},
      {className: 'xds-chat-message-bubble', visualProps: ['sender', 'variant']},
      {className: 'xds-chat-message-list', visualProps: ['density']},
      {className: 'xds-chat-system-message', visualProps: ['variant']},
      {className: 'xds-chat-message-metadata'},
      {className: 'xds-chat-send-button'},
      {className: 'xds-chat-tokenized-text'},
      {className: 'xds-chat-tool-calls'},
      {className: 'xds-trigger-menu'},
    ],
    vars: [
      {name: '--_chat-composer-radius', description: 'Border radius of the composer body. Inner elements derive their radius concentrically.', default: 'var(--radius-page)', private: true},
      {name: '--_chat-composer-padding', description: 'Padding of the composer body. Used in the concentric radius calculation.', default: 'var(--spacing-3)', private: true},
      {name: '--_button-radius', description: 'Concentric button radius inside the composer.', default: 'max(var(--radius-element), calc(var(--_chat-composer-radius) - var(--_chat-composer-padding)))', private: true, derived: true, formula: 'max(var(--radius-element), calc(var(--_chat-composer-radius) - var(--_chat-composer-padding)))'},
    ],
    derived: [
      {property: 'borderRadius', vars: ['--_chat-composer-radius']},
      {property: 'padding', vars: ['--_chat-composer-padding']},
    ],
  },
  components: [
    {
      name: 'XDSChatMessageList',
      description: 'Presentational message container with density context and infinite scroll support. Provides role="log" with aria-live="polite" for accessibility. A flex spacer pushes messages to the bottom when the list isn\'t full.',
      props: [
        {name: 'children', type: 'ReactNode', description: 'Message elements — typically XDSChatMessage or XDSChatSystemMessage.', required: true},
        {name: 'emptyState', type: 'ReactNode', description: 'Content shown when the list has no messages.'},
        {name: 'onScrollToTopAction', type: '() => Promise<void>', description: 'Async action fired when user scrolls to top. Use for loading older messages. Wrapped in useTransition — shows a spinner at the top while pending.'},
        {name: 'density', type: "'compact' | 'balanced' | 'spacious'", description: 'Visual density — flows to child messages via context.', default: "'balanced'"},
      ],
    },
    {
      name: 'XDSChatMessage',
      description: 'Sender context wrapper — handles avatar, name, metadata, and alignment based on sender role.',
      props: [
        {name: 'sender', type: "'user' | 'assistant' | 'system'", description: 'Who sent this message — controls alignment and layout.', required: true},
        {name: 'children', type: 'ReactNode', description: 'Free-form content: bubbles, asset lists, tool calls, images.', required: true},
        {name: 'avatar', type: 'ReactNode', description: 'Avatar element rendered beside the message. Typically XDSAvatar.'},
        {name: 'name', type: 'ReactNode', description: 'Sender name rendered above the message body. Use when the first child is raw content (not a bubble). If the first child is a bubble, put the name on the bubble\'s `name` prop instead.'},
        {name: 'metadata', type: 'ReactNode', description: 'Metadata rendered below the message body. Use when the last child is raw content (not a bubble). If the last child is a bubble, put metadata on the bubble\'s `metadata` prop instead.'},
        {name: 'density', type: "'compact' | 'balanced' | 'spacious'", description: 'Visual density. Inherited from list context if not set.'},
      ],
    },
    {
      name: 'XDSChatMessageBubble',
      description: 'Styled bubble container — reads sender from parent context for auto-styling. Supports name/metadata slots aligned with bubble padding, multi-bubble grouping via `group` prop, and a ghost variant for content that needs alignment without a visual boundary.',
      props: [
        {name: 'children', type: 'ReactNode', description: 'Bubble content — text, XDSMarkdown, or any ReactNode.', required: true},
        {name: 'variant', type: "'filled' | 'ghost'", description: "Visual variant. 'filled' renders sender-colored background (default). 'ghost' renders transparent background but keeps padding for alignment.", default: "'filled'"},
        {name: 'name', type: 'ReactNode', description: "Sender name rendered above the bubble, aligned with bubble text padding. Use on the first bubble in a message. If the first content is raw (no bubble), use XDSChatMessage's `name` prop instead."},
        {name: 'metadata', type: 'ReactNode', description: "Metadata content rendered below the bubble, aligned with bubble text padding. Use on the last bubble in a message. If the last content is raw (no bubble), use XDSChatMessage's `metadata` prop instead."},
        {name: 'group', type: "'first' | 'middle' | 'last'", description: 'Position within a multi-bubble group. Controls corner radius reduction on the sender side. Leave unset for standalone bubbles (full radius).'},
      ],
    },
    {
      name: 'XDSChatMessageMetadata',
      description: 'Composable metadata row for chat messages. Renders timestamp, footer content, and delivery status in a single row. Direction reverses for user sender. Renders nothing if all props are empty.',
      props: [
        {name: 'timestamp', type: 'ReactNode', description: 'Timestamp content — a string or XDSTimestamp component.'},
        {name: 'footer', type: 'ReactNode', description: 'Footer content — model info, reaction buttons, copy button.'},
        {name: 'status', type: "'sending' | 'sent' | 'delivered' | 'read' | 'error'", description: 'Message delivery status. Shows icon + label.'},
      ],
    },
    {
      name: 'XDSChatSystemMessage',
      description: 'Centered system message for non-sender content like date separators, membership changes, and status notices. It is not a chat bubble — it has no avatar, no alignment, and no sender context. Use the divider variant for temporal breaks and default for inline status updates.',
      props: [
        {name: 'children', type: 'ReactNode', description: 'System message content — a short, factual string like a date, a join/leave notice, or a status change.', required: true},
        {name: 'variant', type: "'default' | 'divider'", description: "Visual variant. 'default' renders centered text. 'divider' adds horizontal lines on each side via XDSDivider — use for date separators and section breaks.", default: "'default'"},
        {name: 'icon', type: 'ReactNode', description: 'Leading icon that reinforces the message type. Wrap in XDSIcon for consistent sizing. Use for membership changes, encryption notices, or AI activity.'},
      ],
    },
    {
      name: 'XDSChatComposer',
      description: 'Layout shell for a chat composer. Arranges named slots (drawer, header, input, footer, send) with page-radius container, hover/focus shadows, and concentric inner radius for child elements.',
      props: [
        {name: 'onSubmit', type: '(value: string) => void', description: 'Called when the user submits a message.', required: true},
        {name: 'onStop', type: '() => void', description: 'Called when the user requests to stop generation.'},
        {name: 'isStreaming', type: 'boolean', description: 'Whether the assistant is currently streaming.', default: 'false'},
        {name: 'value', type: 'string', description: 'Controlled input value.'},
        {name: 'onChange', type: '(value: string) => void', description: 'Change handler for controlled mode.'},
        {name: 'placeholder', type: 'string', description: 'Placeholder text.', default: "'Type a message\u2026'"},
        {name: 'isDisabled', type: 'boolean', description: 'Disables the composer.', default: 'false'},
        {name: 'density', type: "'compact' | 'balanced' | 'spacious'", description: 'Visual density.', default: "'balanced'"},
        {name: 'drawer', type: 'ReactNode', description: 'Slot: collapsible drawer above the input — attachments, context chips, etc. Use XDSChatComposerDrawer.'},
        {name: 'headerActions', type: 'ReactNode', description: 'Slot: left-aligned header actions (attach, mention buttons). Use icon-only size="sm" buttons.'},
        {name: 'headerContext', type: 'ReactNode', description: 'Slot: right-aligned contextual info in the header (context window usage, XDSProgressBar, supporting text).'},
        {name: 'input', type: 'ReactNode', description: 'Slot: custom input element. Replaces the default textarea. Use XDSChatComposerInput for trigger menus.'},
        {name: 'footerActions', type: 'ReactNode', description: 'Slot: left-aligned footer actions (model selector, etc).'},
        {name: 'sendActions', type: 'ReactNode', description: 'Slot: actions to the left of the send button.'},
        {name: 'sendButton', type: 'ReactNode', description: 'Slot: custom send button. Replaces the default send/stop button.'},
        {name: 'status', type: "{ type: 'error' | 'warning'; message?: string }", description: 'Status message rendered below (or above) the composer.'},
        {name: 'statusPosition', type: "'top' | 'bottom'", description: 'Where to render the status.', default: "'bottom'"},
      ],
    },
    {
      name: 'XDSChatComposerInput',
      description: 'ContentEditable-based rich input with trigger menus (@ mentions, / commands), inline tokens, serialization, message history, and paste/drop file handling. Uses XDSSearchSource for search. Exposes an imperative handle for programmatic control.',
      props: [
        {name: 'ref', type: 'React.Ref<XDSChatComposerInputHandle>', description: 'Imperative handle ref exposing insertToken, insertText, focus, and getValue.'},
        {name: 'value', type: 'string', description: 'Controlled value.'},
        {name: 'onChange', type: '(value: string) => void', description: 'Change handler.'},
        {name: 'placeholder', type: 'string', description: 'Placeholder text.', default: "'Type a message\u2026'"},
        {name: 'maxRows', type: 'number', description: 'Max rows before scrolling.', default: '8'},
        {name: 'triggers', type: 'XDSChatComposerTrigger[]', description: 'Trigger definitions for menus. Each trigger has a character, searchSource, and onSelect.'},
        {name: 'debounceMs', type: 'number', description: 'Debounce for async search sources.', default: '150'},
        {name: 'hasHistory', type: 'boolean', description: 'Enable ArrowUp/Down message recall.', default: 'true'},
        {name: 'label', type: 'string', description: 'Accessible label.', default: "'Message input'"},
        {name: 'isDisabled', type: 'boolean', description: 'Disabled state.', default: 'false'},
        {name: 'onPaste', type: '(event, text) => void', description: 'Paste handler.'},
        {name: 'onFiles', type: '(files: File[]) => void', description: 'File drop/paste handler.'},
        {name: 'onSubmit', type: '(value: string) => void', description: 'Submit handler (Enter without Shift).'},
      ],
    },
    {
      name: 'XDSChatComposerDrawer',
      description: 'Collapsible drawer panel for the composer. Use for attachments, context chips, or any supplementary content above the input.',
      props: [
        {name: 'children', type: 'ReactNode', description: 'Attachment items to render.', required: true},
        {name: 'count', type: 'number', description: 'Total attachment count. When provided and exceeds visible children, shows a collapse/expand toggle.'},
      ],
    },
    {
      name: 'XDSChatSendButton',
      description: 'Circular send/stop toggle button for the composer. Reads state from XDSChatComposerContext by default so it works automatically inside XDSChatComposer. All context values can be overridden via props for standalone usage.',
      props: [
        {name: 'isStreaming', type: 'boolean', description: 'Whether the assistant is currently streaming. Defaults to context value.'},
        {name: 'isDisabled', type: 'boolean', description: 'Whether the send button is disabled. Defaults to !canSend from context.'},
        {name: 'onSend', type: '() => void', description: 'Called when the user clicks send. Defaults to context onSubmit.'},
        {name: 'onStop', type: '() => void', description: 'Called when the user clicks stop during streaming. Defaults to context onStop.'},
        {name: 'sendIcon', type: 'ReactNode', description: 'Custom icon for the send state. Defaults to arrowUp from icon registry.'},
        {name: 'stopIcon', type: 'ReactNode', description: 'Custom icon for the stop state. Defaults to stop from icon registry.'},
        {name: 'size', type: "'sm' | 'md'", description: 'Button size.', default: "'md'"},
        {name: 'xstyle', type: 'StyleXStyles', description: 'Additional StyleX styles.'},
      ],
    },
    {
      name: 'XDSChatToolCalls',
      description: 'Displays tool/function call invocations from an LLM response. Accepts a `calls` array matching the shape LLM APIs return. Single call renders inline; multiple calls get a collapsible summary with the latest call visible at the surface.',
      props: [
        {name: 'calls', type: 'XDSChatToolCallItem[]', description: 'Array of tool call data. Each item has name, status, target, duration, node, additions, deletions, stats, resultDetail.', required: true},
        {name: 'label', type: 'string', description: 'Custom summary label for groups. Auto-generated from count if omitted.'},
        {name: 'isExpanded', type: 'boolean', description: 'Controlled expanded state.'},
        {name: 'defaultIsExpanded', type: 'boolean', description: 'Default expanded state (uncontrolled).', default: 'false'},
        {name: 'onExpandedChange', type: '(isExpanded: boolean) => void', description: 'Callback when expanded state changes.'},
      ],
    },
    {
      name: 'XDSChatTokenizedText',
      description: 'Renders a text string with token patterns replaced by inline XDSBadge components. Wrap any message body inside XDSChatMessageBubble to turn raw @mentions, #tags, or /commands into styled badges. When no tokens match or none are provided, the text renders as-is — so you can use ChatTokenizedText unconditionally on every message.',
      props: [
        {name: 'children', type: 'string', description: 'The plain text message containing serialized token values. Patterns matching a token\'s value are replaced with badge components inline.', required: true},
        {name: 'tokens', type: 'XDSChatComposerToken[]', description: 'Token definitions — same type returned by trigger onSelect. Each token has a value (the string to match), label (display text), and optional variant and icon. Uses the same type as the composer input, so token definitions work for both input and display.'},
      ],
    },
  ],
  usage: {
    description: 'Chat components provide layout primitives and a message composer for building AI chat interfaces. XDSChatComposer is the input shell — compose it using named slots (drawer, headerActions, footerActions, sendActions) to assemble features like file attachments, model selectors, and context indicators without building custom layout. Use Chat components when building conversational UIs that need message display, sender-aware styling, and rich input with trigger menus and attachments.',
    bestPractices: [
      { guidance: true, description: 'Compose messages using MessageList > Message > Bubble for consistent sender-aware styling and density.' },
      { guidance: true, description: 'Use the named slots on XDSChatComposer (drawer, headerActions, footerActions, sendActions) to keep the input layout structured. Each slot has a specific position and purpose.' },
      { guidance: true, description: 'Show the streaming state with isStreaming and provide an onStop handler so users can cancel long-running responses.' },
      { guidance: true, description: 'Put name and metadata on the bubble when the content has a visible bubble boundary. Put them on the message wrapper when the content is raw (no bubble).' },
      { guidance: true, description: 'Use XDSChatLayout for full-page chat — it handles auto-scroll, density adaptation, and composer docking automatically.' },
      { guidance: true, description: 'Use XDSChatSystemMessage with variant="divider" for date separators and default for status notices like joins, leaves, or topic changes.' },
      { guidance: true, description: 'Add an icon to system messages when the type is not obvious from the text alone — membership changes, encryption notices, or AI activity benefit from visual reinforcement.' },
      { guidance: true, description: 'Use the group prop on bubbles (first, middle, last) when a single sender sends multiple consecutive messages — it tightens corner radius to visually connect them.' },
      { guidance: true, description: 'Use the ghost bubble variant for AI-style responses that need alignment without a visual boundary.' },
      { guidance: false, description: 'Don\'t build custom input containers or composer chrome — XDSChatComposer handles the border radius, shadows, focus ring, and slot layout. Customise through slots, not wrapping.' },
      { guidance: false, description: 'Don\'t place metadata or names on both the bubble and the message wrapper — pick one based on whether the content has a bubble boundary.' },
      { guidance: false, description: 'Don\'t use the status prop for transient success messages — it\'s for errors and warnings that need the user\'s attention before they send another message.' },
      { guidance: false, description: 'Don\'t use XDSChatSystemMessage for sender content — it has no avatar, alignment, or bubble. Use XDSChatMessage with a sender role instead.' },
      { guidance: false, description: 'Don\'t put long or multi-line content in a system message — keep it to a single short sentence. If you need more, use a bubble or a card.' },
      { guidance: false, description: 'Don\'t nest XDSChatMessage inside another XDSChatMessage — each message is a standalone article element with its own sender context.' },
    ],
    anatomy: [
      { name: 'Avatar', required: false, description: 'A sender avatar rendered beside the message. Typically XDSAvatar with size="small". Hidden for system messages.' },
      { name: 'Name', required: false, description: 'Sender name above the message body. Place on the bubble when using bubbles, or on the message wrapper for raw content.' },
      { name: 'Content', required: true, description: 'The message body — one or more XDSChatMessageBubble elements, or any free-form ReactNode like images or tool calls.' },
      { name: 'Metadata', required: false, description: 'Timestamp, delivery status, and footer actions below the message. Place on the last bubble or on the message wrapper.' },
    ],
  },
};

// Append XDSChatLayout and XDSChatLayoutScrollButton to all doc variants
const chatLayoutComponent = {
  name: 'XDSChatLayout',
  description: 'Layout shell for full chat interfaces. Messages flow in normal page flow, composer is fixed to the bottom with a frosted glass dock. Adapts density (compact/balanced/spacious) automatically via container width observation. Includes built-in auto-scroll, a "New messages" scroll-to-bottom button, and a frosted glass blur layer behind the composer. By default the layout root is the scroll container; pass scrollRef to delegate scrolling to a parent element or the document body.',
  props: [
    {name: 'children', type: 'ReactNode', description: 'Message content — typically XDSChatMessageList. Flows naturally in the page and scrolls with the container.', required: true},
    {name: 'composer', type: 'ReactNode', description: 'Composer element — typically XDSChatComposer. Fixed to the bottom with a frosted glass dock.', required: true},
    {name: 'emptyState', type: 'ReactNode', description: 'Content shown when children is empty. Centered vertically in the message area.'},
    {name: 'scrollButton', type: 'ReactNode | null', description: 'Scroll-to-bottom button rendered above the composer. Defaults to XDSChatLayoutScrollButton with auto-scroll integration. Pass null to hide.'},
    {name: 'scrollRef', type: 'React.RefObject<HTMLElement | null>', description: 'External scroll container ref. When provided, auto-scroll and scroll-to-bottom target this element instead of the layout root. Use when the chat is embedded in a page where a parent element or the document body scrolls.'},
  ],
};
docs.components.push(chatLayoutComponent);

const chatLayoutScrollButtonComponent = {
  name: 'XDSChatLayoutScrollButton',
  description: 'Composable scroll-to-bottom button for use inside XDSChatLayout. Fades in when visible, expands to show a label (e.g. "New messages"). Used as the default scrollButton in XDSChatLayout; override via the scrollButton prop.',
  props: [
    {name: 'isVisible', type: 'boolean', description: 'Whether the button is visible.', required: true},
    {name: 'label', type: 'string', description: 'Optional label — expands the button (e.g. "New messages").'},
    {name: 'onClick', type: '() => void', description: 'Click handler — typically scrolls to bottom and dismisses new message indicator.', required: true},
  ],
};
docs.components.push(chatLayoutScrollButtonComponent);

/** @type {import('../docs-types').TranslationDoc} */
export const docsZh = {
  usage: {
    description: 'Chat components provide layout primitives and a message composer for building AI chat interfaces. XDSChatComposer is the input shell — compose it using named slots (drawer, headerActions, footerActions, sendActions) to assemble features like file attachments, model selectors, and context indicators without building custom layout. Use Chat components when building conversational UIs that need message display, sender-aware styling, and rich input with trigger menus and attachments.',
    bestPractices: [
      { guidance: true, description: 'Compose messages using MessageList > Message > Bubble for consistent sender-aware styling and density.' },
      { guidance: true, description: 'Use the named slots on XDSChatComposer (drawer, headerActions, footerActions, sendActions) to keep the input layout structured. Each slot has a specific position and purpose.' },
      { guidance: true, description: 'Show the streaming state with isStreaming and provide an onStop handler so users can cancel long-running responses.' },
      { guidance: true, description: 'Put name and metadata on the bubble when the content has a visible bubble boundary. Put them on the message wrapper when the content is raw (no bubble).' },
      { guidance: true, description: 'Use XDSChatLayout for full-page chat — it handles auto-scroll, density adaptation, and composer docking automatically.' },
      { guidance: true, description: 'Use XDSChatSystemMessage with variant="divider" for date separators and default for status notices like joins, leaves, or topic changes.' },
      { guidance: true, description: 'Add an icon to system messages when the type is not obvious from the text alone — membership changes, encryption notices, or AI activity benefit from visual reinforcement.' },
      { guidance: true, description: 'Use the group prop on bubbles (first, middle, last) when a single sender sends multiple consecutive messages — it tightens corner radius to visually connect them.' },
      { guidance: true, description: 'Use the ghost bubble variant for AI-style responses that need alignment without a visual boundary.' },
      { guidance: false, description: 'Don\'t build custom input containers or composer chrome — XDSChatComposer handles the border radius, shadows, focus ring, and slot layout. Customise through slots, not wrapping.' },
      { guidance: false, description: 'Don\'t place metadata or names on both the bubble and the message wrapper — pick one based on whether the content has a bubble boundary.' },
      { guidance: false, description: 'Don\'t use the status prop for transient success messages — it\'s for errors and warnings that need the user\'s attention before they send another message.' },
      { guidance: false, description: 'Don\'t use XDSChatSystemMessage for sender content — it has no avatar, alignment, or bubble. Use XDSChatMessage with a sender role instead.' },
      { guidance: false, description: 'Don\'t put long or multi-line content in a system message — keep it to a single short sentence. If you need more, use a bubble or a card.' },
      { guidance: false, description: 'Don\'t nest XDSChatMessage inside another XDSChatMessage — each message is a standalone article element with its own sender context.' },
    ],
  },
  components: [
    {
      name: 'XDSChatMessageList',
      description: '消息展示容器，支持密度上下文和无限滚动。自动滚动由 XDSChatLayout 管理。',
      propDescriptions: {
        children: '消息元素，通常是 XDSChatMessage 或 XDSChatSystemMessage。',
        emptyState: '列表无消息时显示的内容。',
        onScrollToTopAction: '用户滚动到顶部时触发的异步操作。用于加载更早的消息。',
        density: '视觉密度，通过上下文传递给子消息。',
      },
    },
    {
      name: 'XDSChatMessage',
      description: '发送者上下文包装器，根据发送者角色处理头像、名称、元数据和对齐方式。',
      propDescriptions: {
        sender: '消息发送者，控制对齐和布局。',
        children: '自由内容：气泡、资源列表、工具调用、图片。',
        avatar: '消息旁边渲染的头像元素。通常是 XDSAvatar。',
        name: '消息正文上方渲染的发送者名称。当第一个子元素不是气泡时使用。',
        metadata: '消息正文下方渲染的元数据。当最后一个子元素不是气泡时使用。',
        density: '视觉密度。未设置时从列表上下文继承。',
      },
    },
    {
      name: 'XDSChatMessageBubble',
      description: '样式化的气泡容器，从父上下文读取发送者信息进行自动样式化。支持 name/metadata 插槽、多气泡分组和透明变体。',
      propDescriptions: {
        children: '气泡内容：文本、XDSMarkdown 或任何 ReactNode。',
        variant: "视觉变体。'filled' 渲染发送者颜色背景，'ghost' 渲染透明背景但保持填充对齐。",
        name: '气泡上方渲染的发送者名称，与气泡文本内边距对齐。用于消息中的第一个气泡。',
        metadata: '气泡下方渲染的元数据内容，与气泡文本内边距对齐。用于消息中的最后一个气泡。',
        group: '多气泡组中的位置。控制发送者侧的圆角缩减。',
      },
    },
    {
      name: 'XDSChatMessageMetadata',
      description: '可组合的消息元数据行。渲染时间戳、页脚内容和发送状态。用户消息方向反转。',
      propDescriptions: {timestamp: '时间戳内容 — 字符串或 XDSTimestamp 组件。', footer: '页脚内容 — 模型信息、反应按钮、复制按钮。', status: '消息发送状态。显示图标和标签。'},
    },
    {
      name: 'XDSChatSystemMessage',
      description: '居中的系统消息，用于日期分隔、成员变更和状态通知等非发送者内容。没有头像、对齐或气泡。使用 divider 变体做时间分隔，default 做内联状态更新。',
      propDescriptions: {children: '系统消息内容 — 简短的事实性文本，如日期、加入/离开通知或状态变更。', variant: "视觉变体。'default' 渲染居中文本。'divider' 通过 XDSDivider 在两侧添加水平线 — 用于日期分隔和段落分隔。", icon: '增强消息类型辨识度的前置图标。使用 XDSIcon 包裹以获得一致的尺寸。'},
    },
    {
      name: 'XDSChatComposer',
      description: '聊天编写器布局外壳。排列命名插槽（附件、标题栏、输入、页脚、发送），带有页面圆角容器和同心内圆角。',
      propDescriptions: {
        onSubmit: '用户提交消息时调用。',
        onStop: '用户请求停止生成时调用。',
        isStreaming: '助手是否正在流式输出。',
        value: '受控输入值。',
        onChange: '受控模式的变更处理器。',
        placeholder: '占位文本。',
        isDisabled: '禁用编写器。',
        density: '视觉密度。',
        drawer: '插槽：输入上方的可折叠抽屉——附件、上下文标签等。使用 XDSChatComposerDrawer。',
        headerActions: '插槽：标题左侧操作按钮（附件、提及按钮）。使用仅图标 size="sm" 按钮。',
        headerContext: '插槽：标题右侧上下文信息（上下文窗口使用情况、XDSProgressBar、辅助文本）。',
        input: '插槽：自定义输入元素。替换默认文本区域。使用 XDSChatComposerInput 实现触发菜单。',
        footerActions: '插槽：左对齐的页脚操作（模型选择器等）。',
        sendActions: '插槽：发送按钮左侧的操作。',
        sendButton: '插槽：自定义发送按钮。替换默认的发送/停止按钮。',
        status: '编写器下方（或上方）的状态消息。',
        statusPosition: '状态渲染位置。',
      },
    },
    {
      name: 'XDSChatComposerInput',
      description:
        '基于 ContentEditable 的富文本输入，支持触发菜单（@ 提及、/ 命令）、内联标记、序列化、消息历史和粘贴/拖放文件处理。提供命令式句柄用于编程式控制。',
      propDescriptions: {
        ref: '命令式句柄引用，暴露 insertToken、insertText、focus 和 getValue。',
        value: '受控值。',
        onChange: '变更处理器。',
        placeholder: '占位文本。',
        maxRows: '滚动前的最大行数。',
        triggers: '菜单的触发定义。每个触发器有 character、searchSource 和 onSelect。',
        debounceMs: '异步搜索源的去抖动延迟。',
        hasHistory: '启用 ArrowUp/Down 消息回溯。',
        label: '无障碍标签。',
        isDisabled: '禁用状态。',
        onPaste: '粘贴处理器。',
        onFiles: '文件拖放/粘贴处理器。',
        onSubmit: '提交处理器（不按 Shift 的 Enter）。',
      },
    },
    {
      name: 'XDSChatComposerDrawer',
      description: '编写器的可折叠抽屉面板。用于附件、上下文标签或输入上方的任何补充内容。',
      propDescriptions: {children: '要渲染的附件项目。', count: '附件总数。超过可见子元素时显示折叠/展开切换。'},
    },
    {
      name: 'XDSChatSendButton',
      description:
        '编写器的圆形发送/停止切换按钮。默认从 XDSChatComposerContext 读取状态，在 XDSChatComposer 内自动工作。所有上下文值均可通过 props 覆盖以用于独立使用。',
      propDescriptions: {
        isStreaming: '助手是否正在流式响应。默认使用上下文值。',
        isDisabled: '发送按钮是否禁用。默认使用上下文的 !canSend。',
        onSend: '用户点击发送时调用。默认使用上下文的 onSubmit。',
        onStop: '流式响应期间用户点击停止时调用。默认使用上下文的 onStop。',
        sendIcon: '发送状态的自定义图标。默认使用图标注册表的 arrowUp。',
        stopIcon: '停止状态的自定义图标。默认使用图标注册表的 stop。',
        size: '按钮大小。',
        xstyle: '额外的 StyleX 样式。',
      },
    },
    {
      name: 'XDSChatToolCalls',
      description:
        '显示 LLM 响应中的工具/函数调用。接受与 LLM API 返回形状匹配的 calls 数组。单个调用内联渲染；多个调用显示可折叠摘要。',
      propDescriptions: {
        calls:
          '工具调用数据数组。每项包含 name、status、target、duration、node、additions、deletions、stats、resultDetail。',
        label: '组的自定义摘要标签。省略时从数量自动生成。',
        isExpanded: '受控展开状态。',
        defaultIsExpanded: '默认展开状态（非受控）。',
        onExpandedChange: '展开状态变更时的回调。',
      },
    },
    {
      name: 'XDSChatTokenizedText',
      description:
        '渲染带有标记模式的文本，将匹配的模式替换为内联 XDSBadge 组件。在 XDSChatMessageBubble 内使用，将 @提及、#标签或 /命令显示为样式化徽章。未提供标记时以纯文本渲染，因此可以无条件使用。',
      propDescriptions: {children: '包含序列化标记值的纯文本消息。匹配标记值的模式将被替换为内联徽章组件。', tokens: '标记定义 — 与触发器 onSelect 返回的类型相同。每个包含 value（匹配字符串）、label（显示文本）以及可选的 variant 和 icon。'},
    },
    {
      name: 'XDSChatLayout',
      description: '完整聊天界面的布局外壳。消息在页面中自然流动，编写器固定在底部，带有毛玻璃效果。通过容器宽度自动适配密度。',
      propDescriptions: {
        children: '消息内容 — 通常是 XDSChatMessageList。在页面中自然流动。',
        composer: '编写器元素 — 通常是 XDSChatComposer。固定在底部，带有毛玻璃底座。',
        emptyState: '子元素为空时显示的内容。',
        scrollButton: '编写器上方的滚动到底部按钮。默认使用 XDSChatLayoutScrollButton。传入 null 隐藏。',
        scrollRef: '外部滚动容器引用。提供时，自动滚动和滚动到底部将目标指向此元素。',
      },
    },
    {
      name: 'XDSChatLayoutScrollButton',
      description: '可组合的滚动到底部按钮。可见时淡入，提供标签时展开。',
      propDescriptions: {isVisible: '按钮是否可见。', label: '可选标签 — 展开按钮（如"新消息"）。', onClick: '点击处理器。'},
    },
  ],
};

/** @type {import('../docs-types').TranslationDoc} */
export const docsDense = {
  description: 'AI chat components. Layout (MessageList>Message>Bubble+SystemMessage) + Composer (shell w/ slots, ContentEditable input w/ trigger menus, attachments)',
  usage: {
    description: 'Chat layout primitives + composer for AI chat UIs. Composer is a slot-based shell — drawer, headerActions, footerActions, sendActions. Use Chat components for conversational UIs w/ message display, sender-aware styling, rich input.',
    bestPractices: [
      { guidance: true, description: 'MessageList > Message > Bubble for sender-aware styling.' },
      { guidance: true, description: 'Named slots on Composer (drawer, headerActions, footerActions, sendActions) — each has a specific position.' },
      { guidance: true, description: 'isStreaming + onStop for cancelable long-running responses.' },
      { guidance: true, description: 'Name/metadata on bubble if bubble boundary, on message wrapper if raw content.' },
      { guidance: true, description: 'XDSChatLayout for full-page — auto-scroll, density adaptation, composer docking.' },
      { guidance: true, description: 'SystemMessage: divider variant for date breaks, default for status notices. Add icon for membership/encryption/AI messages.' },
      { guidance: true, description: 'Group prop on bubbles (first/middle/last) for consecutive same-sender messages — tightens corner radius.' },
      { guidance: true, description: 'Ghost bubble variant for AI-style responses without a visual boundary.' },
      { guidance: false, description: 'Custom composer chrome — Composer handles radius, shadows, focus ring. Use slots.' },
      { guidance: false, description: 'Metadata/names on both bubble and wrapper — pick one.' },
      { guidance: false, description: 'Status for success toasts — it\'s for errors/warnings before next send.' },
      { guidance: false, description: 'SystemMessage for sender content — no avatar/alignment/bubble. Use ChatMessage instead.' },
      { guidance: false, description: 'Long/multi-line system messages — keep to a single short sentence.' },
      { guidance: false, description: 'Nesting XDSChatMessage inside another — each is a standalone article.' },
    ],
  },
  components: [
    {
      name: 'XDSChatMessageList',
      description: 'presentational msg container w/ density context + infinite scroll; auto-scroll owned by XDSChatLayout',
      propDescriptions: {
        children: 'msg elements (XDSChatMessage or XDSChatSystemMessage)',
        emptyState: 'content when no msgs',
        onScrollToTopAction: 'async action at scroll top; load older msgs',
        density: 'visual density; flows to children via context',
      },
    },
    {
      name: 'XDSChatMessage',
      description: 'sender context wrapper; handles avatar+name+metadata+alignment by sender role',
      propDescriptions: {
        sender: 'who sent; controls alignment+layout',
        children: 'free-form: bubbles, assets, tool calls, images',
        avatar: 'avatar element beside msg; typically XDSAvatar',
        name: 'sender name above body; use when first child is raw (not bubble)',
        metadata: 'metadata below body; use when last child is raw (not bubble)',
        density: 'visual density; inherited from list context if unset',
      },
    },
    {
      name: 'XDSChatMessageBubble',
      description: 'styled bubble container; reads sender from context; supports name/metadata slots, group corners, ghost variant',
      propDescriptions: {
        children: 'bubble content: text, XDSMarkdown, any ReactNode',
        variant: "filled (sender bg) or ghost (transparent, keeps padding)",
        name: 'sender name above bubble, aligned w/ bubble padding',
        metadata: 'metadata below bubble, aligned w/ bubble padding',
        group: "position in multi-bubble group; controls corner radius reduction",
      },
    },
    {
      name: 'XDSChatMessageMetadata',
      description: 'composable metadata row; renders timestamp · footer · status; reverses for user sender',
      propDescriptions: {
        timestamp: 'timestamp content; string or XDSTimestamp',
        footer: 'footer content; model info, reaction btns, copy btn',
        status: 'delivery status; shows icon+label',
      },
    },
    {
      name: 'XDSChatSystemMessage',
      description: 'centered non-sender msg; divider variant for date breaks, default for status notices; supports leading icon',
      propDescriptions: {
        children: 'short factual text: date, join/leave, status change',
        variant: "default=centered text, divider=horizontal lines via XDSDivider for date/section breaks",
        icon: 'leading icon reinforcing msg type; wrap in XDSIcon',
      },
    },
    {
      name: 'XDSChatComposer',
      description: 'composer layout shell; named slots (drawer/header/input/footer/send) w/ page-radius + concentric inner radius',
      propDescriptions: {
        onSubmit: 'submit msg handler',
        onStop: 'stop generation handler',
        isStreaming: 'assistant streaming state',
        value: 'controlled input value',
        onChange: 'controlled change handler',
        placeholder: 'placeholder text',
        isDisabled: 'disabled state',
        density: 'visual density',
        drawer: 'slot: collapsible drawer above input — attachments, context chips, etc.; use XDSChatComposerDrawer',
        headerActions: 'slot: left header actions (attach, mention); icon-only sm buttons',
        headerContext: 'slot: right header context info (window usage, XDSProgressBar, text)',
        input: 'slot: custom input; replaces default textarea; use XDSChatComposerInput for triggers',
        footerActions: 'slot: left footer actions (model selector etc)',
        sendActions: 'slot: actions left of send btn',
        sendButton: 'slot: custom send btn; replaces default',
        status: 'status msg below/above composer',
        statusPosition: 'status render position',
      },
    },
    {
      name: 'XDSChatComposerInput',
      description: 'ContentEditable rich input w/ trigger menus (@/commands), inline tokens, serialization, msg history, paste/drop files, imperative handle',
      propDescriptions: {
        ref: 'imperative handle ref (insertToken/insertText/focus/getValue)',
        value: 'controlled value',
        onChange: 'change handler',
        placeholder: 'placeholder text',
        maxRows: 'max rows before scrolling',
        triggers: 'trigger defs for menus; each has character+searchSource+onSelect',
        debounceMs: 'debounce for async search sources',
        hasHistory: 'ArrowUp/Down msg recall',
        label: 'a11y label',
        isDisabled: 'disabled state',
        onPaste: 'paste handler',
        onFiles: 'file drop/paste handler',
        onSubmit: 'submit handler (Enter w/o Shift)',
      },
    },
    {
      name: 'XDSChatComposerDrawer',
      description: 'collapsible drawer panel for composer; use for attachments, context chips, or supplementary content',
      propDescriptions: {
        children: 'attachment items to render',
        count: 'total count; shows collapse/expand when exceeds visible',
      },
    },
    {
      name: 'XDSChatSendButton',
      description: 'circular send/stop toggle btn for composer; reads XDSChatComposerContext; all context vals overridable via props',
      propDescriptions: {
        isStreaming: 'streaming state; defaults to context',
        isDisabled: 'disabled; defaults to !canSend from context',
        onSend: 'send click handler; defaults to context onSubmit',
        onStop: 'stop click handler; defaults to context onStop',
        sendIcon: 'custom send icon; default arrowUp from registry',
        stopIcon: 'custom stop icon; default stop from registry',
        size: 'btn size',
        xstyle: 'additional StyleX styles',
      },
    },
    {
      name: 'XDSChatToolCalls',
      description: 'tool/function call display from LLM response; single=inline, multiple=collapsible summary',
      propDescriptions: {
        calls: 'tool call data array; name+status+target+duration+node+additions+deletions+resultDetail',
        label: 'custom summary label; auto from count if omitted',
        isExpanded: 'controlled expanded state',
        defaultIsExpanded: 'default expanded state (uncontrolled)',
        onExpandedChange: 'expanded state change callback',
      },
    },
    {
      name: 'XDSChatTokenizedText',
      description: 'renders text w/ token patterns replaced by inline badges; use in bubble for @mentions, #tags, /commands; degrades to plain text when no tokens match',
      propDescriptions: {
        children: 'plain text msg w/ serialized token values; matching patterns become inline badges',
        tokens: 'token defs (same type as composer input): value+label+variant+icon',
      },
    },
    {
      name: 'XDSChatLayout',
      description: 'layout shell for full chat; msgs in page flow, composer fixed bottom w/ frosted glass dock; auto density via container width; scrollRef delegates to parent/body',
      propDescriptions: {
        children: 'msg content; typically XDSChatMessageList',
        composer: 'composer element; typically XDSChatComposer; fixed bottom w/ frosted glass',
        emptyState: 'content when children empty',
        scrollButton: 'scroll-to-bottom btn; defaults to XDSChatLayoutScrollButton; pass null to hide',
        scrollRef: 'external scroll container ref; targets parent/body instead of layout root',
      },
    },
    {
      name: 'XDSChatLayoutScrollButton',
      description: 'composable scroll-to-bottom btn; fades in when visible, expands w/ label',
      propDescriptions: {
        isVisible: 'btn visibility',
        label: 'optional label; expands btn (e.g. "New messages")',
        onClick: 'click handler',
      },
    },
  ],
};
